Cray-HPE/sat

CHANGELOG.md, tests/test_config.py
This commit changes the unit tests for generate_default_config
so that os.fchmod is mocked out, and the tests assert it is called
as expected.
CRAYSAT-1487
Ran unit tests
=> CRAYSAT-1486: Fix unit tests in PyCharm

CHANGELOG.md, docs/man/sat-bootsys.8.rst, docs/man/sat-status.8.rst
Documented `--bos-version` in relevant subcommand man pages.
* Additional change for work related to epic CRAYSAT-1376
* Local development machine
Build man pages, inspect output manually to ensure proper text and
formatting
None
=> CRAYSAT-1376: Document --bos-version in relevant man pages

sat/cli/swap/blade.py
This change supports swapping Hill hardware in the same manner as
Mountain hardware. Previously this would not work as `sat swap blade`
explicitly checked only for "River" and "Mountain", and "Hill" was
excluded arbitrarily.
* Discovered while testing [CRAYSAT-1446](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1446)
* `rocket`
Use `sat swap blade -a disable` to swap out two blades on a Hill system.
Physically swap the blades. Use `sat swap blade -a enable` to swap back
in the blades, and boot to finish the test. Run unit tests.
None.
=> CRAYSAT-1446: Support Hill hardware in the same manner as Mountain hardware

CHANGELOG.md
This commit declares version 3.18.0 of SAT in the change log. It
also makes some minor formatting updates to the new section of the
change log.
=> CRAYSAT-1525: Update change log and declare new minor version

CHANGELOG.md, requirements.lock.txt, requirements.txt, sat/cli/bootprep/validate.py, sat/recipe.py, tests/test_recipe.py
This change removes the deprecated `distutils` version handling features
and replaces them with the `packaging` library. HPC Software Version
handling and schema version validation were affected.
* Resolves [CRAYSAT-1488](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1488)
* `vale`
Run unit tests. Test on vale with `sat bootprep run --recipe-version
latest` and ensure that the 22.07 recipe is treated as "latest" over an
example 22.07rc1 recipe.
N/A
=> CRAYSAT-1488: Replace `distutils` version handling with `packaging`

sat/recipe.py, tests/test_recipe.py
The name of the repository created to contain recipe information was
changed to hpc-shasta-software-recipe, so change the name used by the
`sat bootprep` code to match.
* Part of [CRAYSAT-1502]()
* N/A
Minor change. Will be tested with integration of SAT with new
hpc-shasta-software-recipe release distribution prior to merge of
feature branch to integration.
Low risk, fixing a mismatch between sat and hpc-shasta-software-recipe.
=> CRAYSAT-1502: Update the name of the VCS repo

CHANGELOG.md, docs/man/sat-bootprep.8.rst, sat/cli/bootprep/image.py, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/image.py, sat/cli/bootprep/input/instance.py, sat/cli/bootprep/input/session_template.py, sat/cli/bootprep/main.py, sat/cli/bootprep/parser.py, sat/cli/bootprep/vars.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/test_validate.py
Add the ability to use the name of the base image or recipe that was
used to construct an image as a variable when templating the `name`
property of an image.
Add the ability to use the name of the image as a variable when
templating the `name` property of a session template.
Since names of session templates and images are now templated and not
required to be unique and cannot be rendered until the base is
validated, change the `__str__` methods of both `InputSessionTemplate`
and `BaseInputImage` to simply state the index of the item in the input
instance.
Also add general variable substitution (e.g. product versions) to the
`conifguration` property for images and to the `name`, `image`, and
`configuration` properties of session templates.
Since image names are now templated using …
=> CRAYSAT-1411: Refactor image dependencies and add name templating

CHANGELOG.md, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/session_template.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/test_validate.py
Add functionality to `sat bootprep` to allow session templates in the
input file to refer to images by their `ref_name` value. This is a
usability improvement to make it easier to refer to an image which has a
name that uses its base image or recipe name in its name.
Deprecate the old way of specifying the IMS image name or ID as a string
in the session template. Add the ability to specify an object under the
`image` property that has either an `ims` property or an `image_ref`
property. The value of the `ims` property is a dict with either a `name`
or an `id` property. The value of the `image_ref` property is a string
that refers to an image in the input file by the value of its `ref_name`
property.
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure …
=> CRAYSAT-1410: Allow session templates to refer to images by ref_name

CHANGELOG.md, sat/config.py, tests/cli/bootsys/test_bos.py
This change updates the default version of BOS to "v2" in the config
file.
* Resolves [CRAYSAT-1463](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1463)
(Functionality relating to BOS v2 has already been tested.)
N/A.
=> CRAYSAT-1463: Switch default BOS version to v2

CHANGELOG.md, docs/man/sat-bootsys.8.rst
The ordering of NCN power operations in the boot phase of `sat bootsys` was fixed. See Ryan's comment [here](https://github.com/Cray-HPE/sat/pull/36#discussion_r949647100).
* Resolves [CRAYSAT-1480](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1480)
Build man pages and inspect.
N/A.
=> CRAYSAT-1480: Fix ordering of NCN power operations

CHANGELOG.md, sat/config.py, tests/cli/bootsys/test_bos.py
This reverts commit e7dc853bdff03876722bd1c783b2cf4a39467f88.
Revert the default BOS API version to "v1".
* Resolves [CRAYSAT-1547](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1547)
* `groot`
Run unit tests. Simply run `sat status --bos-fields` and check that an error is shown saying it only supports BOS v2. Try with `--bos-version=v2` to check that toggling works as expected.
We would like to stay in line with the behavior of the `cray` CLI.
=> Revert "CRAYSAT-1463: Switch default BOS version to v2"

CHANGELOG.md, sat/parser.py
This commit removes setting `exit_on_error` to `False` in the
`parse_known_args` method of `sat.parser.SATArgParser`. Add
a change log entry.
* I installed SAT into a virtualenv with Python 3.9
* I ran SAT with an invalid subcommand and verified that a succinct
error message was printed.
* I ran SAT with a valid subcommand but an invalid option and verified
that the help text for the subcommand was printed.
* I ran SAT with both an invalid subcommand and invalid option and
verified it behaved the same as just giving the invalid subcommand.
* Resolves [CRAYSAT-1546](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1546)
See …
=> CRAYSAT-1546: Fix traceback on invalid subcommand

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/validate.py, sat/recipe.py, tests/test_recipe.py
This change changes version comparison for Shasta Software Recipes and
bootprep schemas to use the `semver` library instead of the `packaging`
library, which uses the PEP 440 versioning scheme.
* Resolves [CRAYSAT-1537](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1537)
* `loki`
Run unit tests. Run on system with software recipe installed, and
push various "release" and "prerelease" branches to ensure their
ordering is handled properly.
N/A
=> CRAYSAT-1537: Handle version comparisons using semver

CHANGELOG.md, sat/recipe.py, tests/test_recipe.py
Rename software recipe to hpc-csm-software-recipe subce it's been decided that "shasta" shouldn't be in the name of the repo.
This change is not backwards compatible with older versions of the software recipe, but that's okay because new versions of the software recipe will include this new version of `sat`, and older versions of the recipe will include old versions of `sat`.
* Resolves [CRAYSAT-1552](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1552)
* surtur
Waited for Jenkins build. Exported SAT_IMAGE on surtur and ran `sat
bootprep` against an input file that used a version from the
`product_vars.yaml` file in the VCS repo for the recipe.
No known issues.
=> CRAYSAT-1552: Rename software recipe to hpc-csm-software-recipe

CHANGELOG.md, docs/man/sat-jobstat.8.rst, sat/apiclient/jobstat.py, sat/cli/jobstat/main.py, sat/cli/jobstat/parser.py
This commit implements `sat jobstat`. This command gets a system-wide view of
applications and displays it in a pretty table format. This commit also adds
a change log entry and man page for the command.
=> PE-42104 - Adding Jobstat to SAT CLI (continuation of PR-38)

CHANGELOG.md, requirements.txt, sat/apiclient/ims.py, sat/cli/bootprep/main.py
This commit changes the method of copying from using boto3 S3.Object.copy_from to using boto3 s3.Object.copy, which handles large files better.
Additionally, this change imports botocore.exceptions.ClientError and catches it in the same places that Boto3Error is caught, so that future failures will be logged appropriately rather than failing with a traceback. As a result of importing this exception, botocore is added to the list of top-level dependencies in requirements.txt
Finally, this commit adds a change log entry.
Test Description: After building this image in Jenkins, asked an admin to re-run `sat bootprep` with the value of SAT_IMAGE set to the resulting build.
See commit message
[CASMTRIAGE-4288](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4288)
See commit message
=> CASMTRIAGE-4288: Fix bootprep error in copying image

CHANGELOG.md, sat/cli/bootprep/image.py, sat/cli/bootprep/input/session_template.py, sat/cli/swap/blade.py
This change uses the `raise_not_ok` option in implementations of `sat swap blade` and the validators for `sat bootprep`. This allows easier changes to behavior based on HTTP status codes.
* Resolves [CRAYSAT-1539](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1539)
* `mug`
Run unit tests. Manually perform regression test for `sat bootprep`.
_Are there known issues with these changes? Any other special considerations?_
=> CRAYSAT-1539: Use raise_not_ok API in subcommand implementations

CHANGELOG.md, sat/config.py, tests/test_config.py
This change fixes a bug which caused an error when the config file path was not prefixed with the current directory '.' as the dirname component of the path.
* Resolves [CRAYSAT-1414](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1414)
`sat init -o foo.toml`
None
=> CRAYSAT-1414: Fix `sat init` bug preventing config creation

CHANGELOG.md, sat/cli/bootprep/main.py, sat/cli/bootprep/parser.py, sat/cli/bootprep/vars.py, sat/util.py, setup.py, tests/cli/bootprep/test_vars.py, tests/test_util.py
This change adds a new `list-vars` subcommand to `sat bootprep`. This new subcommand dynamically lists the variables available for use in a bootprep input file given the software recipe, vars file, and command line arguments in use at runtime. Variables are listed by what set them and by their fully-qualified dot-separated name, as they would appear in a bootprep input file, along with their literal values.
* Resolves [CRAYSAT-1532](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1532)
* `mug`
Run unit tests, run various `list-vars` invocations on internal system to test behavior with vars files and command line variables.
Low risk, no changes to core bootprep functionality. …
=> CRAYSAT-1532: Add `sat bootprep list-vars` subcommand

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
This change updates the csm-api-client dependency version to fix a minor type-checking issue where the `APIGatewayClient.set_timeout()` parameter was `int` instead of `Optional[int]`.
* Resolves [CRAYSAT-1593](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1593)
Run unit tests, check type checker output.
None
=> CRAYSAT-1593: Update csm-api-client version

sat/cli/bootprep/main.py
Fix a small issue in https://github.com/Cray-HPE/sat/pull/67 which caused formatting options to not be respected.
* Resolves [CRAYSAT-1532](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1532)
* `mug`
Run on mug with `--filter`, `--format`, `--fields`, `--no-headings`, `--no-borders`, etc.
None
=> CRAYSAT-1532: Respect formatting options in `sat bootprep list-vars`

docker_scripts/config-docker-sat.sh
The build script `docker_scripts/config-docker-sat.sh` was failing because it was attempting to clone a repository that was assumed to be public over HTTP, in order to get the correct version of `kubectl` to put in the SAT image.
This commit changes the script to clone a different repository (which has remained public) to get that information.
* I built the image locally and in Jenkins.
* I verified the version of `kubectl` in `csm-rpms` (new repository) matches the version of `kubectl` currently in `node-images` (old repository).
CRAYSAT-1616
See commit message
=> CRAYSAT-1616: Fix SAT cloning CSM repo to get kubectl version

Dockerfile, Jenkinsfile.github, Makefile
This commit adds authenticated access when accessing the csm-python-modules repository on artifactory.algol60.net. To do this, a `.netrc` file containing read-only credentials is mounted into the container at build time. This follows an example given by the CASM devops team (See: CASMINST-5443).
Test Description: Built image locally and in Jenkins
=> CRAYSAT-1620: Use authentication when accessing csm-python-modules

requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
Use a newer version of csm-api-client which fixes an issue with the `json` kwarg being dropped from calls to `APIGatewayClient.patch`.
This fixes an issue seen when `sat bootprep` renames images after customizing them.
* Resolves [CRAYSAT-1650](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1650)
* frigg
Will test an image customization on frigg with the cray-sat container image built from this branch.
Low risk.
=> CRAYSAT-1650: Use fixed version of csm-api-client package

CHANGELOG.md, sat/cli/bootprep/image.py, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/configuration.py, sat/cli/bootprep/input/image.py, sat/cli/bootprep/input/session_template.py, sat/cli/bootprep/main.py, sat/cli/bootprep/parser.py, sat/report.py, tests/cli/bootprep/input/test_base.py, tests/cli/bootprep/test_main.py, tests/test_report.py
This change adds a reporting capability to `sat bootprep` which reports
which items (configs, images, and session templates) were created during
a sat bootprep run. This information is printed as a report and its
format can be set to 'pretty', 'yaml' or 'json' based on the context of
the run. (For instance, JSON output is useful for IUF runs, where a
pretty report is more useful for end-user runs.) Unit tests for the new 
functionality in the BaseInputItem class were also added.
This change also refactors the Report class to make it easier to dump JSON
and YAML reports. This change also adds a new MultiReport class which
acts as a container for multiple Reports such that they have consistent
formatting and display options. This can also be reused for other
applications where multiple …
=> CRAYSAT-1319: Add report output for `sat bootprep` results

CHANGELOG.md, sat/cli/bootprep/input/configuration.py, tests/cli/bootprep/input/test_configuration.py
Add the ability to render the playbook property of each CFS configuration layer in the bootprep input file using Jinja2. This will allow for variable substitution in playbooks, which is useful to support the two alternative playbooks for the SHS CFS configuration layer.
Add unit tests to check whether this renders correctly.
* Resolves [CRAYSAT-1648](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1648)
* Merge before doc changes here: https://github.com/Cray-HPE/docs-sat/pull/64
* frigg
Unit tests and pycodestyle pass. Will test on frigg.
Low risk.
=> CRAYSAT-1648: Render playbook in CFS config layers in bootprep

CHANGELOG.md, docs/man/sat-bootprep.8.rst, sat/cli/bootprep/constants.py, sat/cli/bootprep/image.py, sat/cli/bootprep/input/instance.py, sat/cli/bootprep/input/session_template.py, sat/cli/bootprep/main.py, sat/cli/bootprep/parser.py, tests/cli/bootprep/test_main.py
Implement a `--limit` option that allows the user to limit which types
of items from the input file are created. For example, the admin can
choose to create only the CFS configurations or only the IMS images and
BOS session templates.
This functionality is needed by the IUF because the stages are split
into `update_cfs_config` which will create the CFS configurations and
`prepare_images` which will create and configure IMS images and create
BOS session templates.
Also created constants for the keys in the input file and used it when
reading those properties from the input file and as the possible values
for the `--limit` option.
* Resolves [CRAYSAT-1606](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1606)
Not tested yet.
* frigg
New feature being added to some complicated code. …
=> CRAYSAT-1606: Implement `--limit` option to `sat bootprep run`

CHANGELOG.md, sat/apiclient/fas.py, sat/logging.py, tests/apiclient/test_fas.py, tests/test_logging.py
As a result of refactoring SAT to use the common CSM python client, `sat firmware` changed the data it was passing to the FASClient post() method, from passing a serialized JSON object to passing a Python dictionary of the data.
To account for this change, the post() method should take the payload data with the json parameter rather than the payload parameter.
This commit also updates the relevant unit tests, and adds a change log entry.
Test Description: I ran `sat firmware -x <xname>` locally with my development machine targeting shandy. After reproducing the error, I verified that the commit fixes the issue.
See commit message
* Resolves CRAYSAT-1647
See commit message
=> CRAYSAT-1647: Pass FAS snapshot payload with json parameter

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/apiclient/bos.py, sat/cli/bootsys/bos.py, sat/cli/bootsys/parser.py, tests/cli/bootsys/test_bos.py
* This PR introduces an option called `--staged-session` which makes use of the `stage` parameter to BOS V2 session creation, in order to stage sessions. Staged sessions update a component's "staged_state" rather than their "desired_state", and as a result staged sessions do not reach "complete" state until after a separate API endpoint is used.
* Resolves CRAYSAT-1657
Tested on frigg. See test description in commit message.
This change should be a relatively low-risk change as I was able to test the `bos-operations` stage thoroughly.
=> CRAYSAT-1657: Add staged boot to bootsys

CHANGELOG.md, sat/cli/bootprep/input/image.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/input/test_image.py, tests/cli/bootprep/test_validate.py
If a product provides more than one image or recipe, it was previously impossible to specify any image or recipe provided by that product. Now it is possible for the admin to differentiate which image they intended by specifying a prefix which will be matched against the name of the image or recipes delivered by that product.
This is needed to support selecting between the Kubernetes image for masters and workers and the storage image for storage nodes, both of which are delivered by CSM and can be differentiated by a prefix.
* Resolves [CRAYSAT-1659](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1659)
* Still needs to be documented in docs-sat
* Local development …
=> CRAYSAT-1659: Add ability to filter product images/recipes by prefix

CHANGELOG.md, sat/cli/bootprep/vars.py, tests/cli/bootprep/test_vars.py
This commit changes how bootprep variables are processed. This applies to variables defined in the software recipe, variables provided on the command line, and variables in local files (i.e. passed in with --vars-file).
This changes top-level keys of dictionaries to replace hyphens with underscores. This gives us the ability to support product names that contain hyphens. To refer to a product name that contains hyphens, the bootprep input file will need to refer to that product with its hyphens replaced with underscores.
Test Description: I ran sat bootprep using an input file that creates a CFS configuration. Then, using `--save-files` I inspected the resulting configuration that was created locally.
With a vars file containing a product with a hyphenated name:
sat bootprep run --dry-run …
=> CRAYSAT-1653: Replace hyphens with underscores in top-level keys

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/parser.py
Fix the missing `--bos-shutdown-timeout` and `--bos-boot-timeout` options on the `sat bootsys reboot` action.
Built and examined man page. Examined output of `sat bootsys reboot --help`.
=> CRAYSAT-1664: Enable bos timeouts on reboot action

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/parser.py
CRAYSAT-1664: Enable bos timeouts on reboot action
Merge pull request #100 from Cray-HPE/CRAYSAT-1664-enable-bos-timeouts-on-reboot
=> Merge from integration_2023-01-30_12.12 to main (Cray-HPE/sat) 01-30

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/auth/main.py
Updating the csm-api-client library version fixes a bug which prevented new token files from being written, breaking authentication.
* Resolves [CRAYSAT-1678](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1678)
* `gamora`
Run `sat auth` against empty config directory and test that the token files are properly created.
=> CRAYSAT-1678: Update csm-api-client library version

CHANGELOG.md, sat/cli/bootsys/bos.py, tests/cli/bootsys/test_bos.py
* Ensure Role_Subrole form found in BOS boot sets is translated to the appropriate HSM parameters.
* Change waiter code to accept either form of 'timed out' indication in the k8s CLI. Add a comment justifying why we continue to scrape CLI output.
* Add unit tests in TestGetTemplatesNeedingOperation that mock out the behavior of HSM to test more thoroughly.
* Add unit tests for the BOSSessionThread.run() method that call the monitor_status_kubectl method.
* Used `sat bootsys boot --stage bos-operations` with a UAN session template that used the 'Application_UAN' format.
* Tested new monitor_status_kubectl behavior by adding unit tests.
=> CRAYSAT-1625: Fixes for bos-sessions stage of sat bootsys

CHANGELOG.md, Dockerfile, requirements-dev.lock.txt, requirements.lock.txt, sat/config.py
Backport needed fixes to release/3.21 branch, so an official 3.21.3 release is created and can be included in SAT 2.5 product stream and CSM 1.4.0.
* Resolves [CRAYSAT-1698](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1698)
* Resolves [CRAYSAT-1699](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1699)
* [CRAYSAT-1700](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1700)
* Documentation PR is coming.
Still need to do a sanity test with the cray-sat container image resulting from the Jenkins build.
* odin (TODO)
Will test `sat status` and `sat bash`.
Low risk changes. The BOS version can still be configured to be BOS v1 at the admin's discretion.
=> CRAYSAT-1698, CRAYSAT-1699, CRAYSAT-1700: Backport to release/3.21

CHANGELOG.md, sat/config.py
This change updates the default version of BOS to "v2" in the config file.
(cherry picked from commit e7dc853bdff03876722bd1c783b2cf4a39467f88)
* Resolves [CRAYSAT-1700](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1700)
* A docs-sat PR will be opened to update the docs accordingly.
* local macbook
Ran `sat status` on local macbook in a Python virtualenv with my sat
config file pointing at Odin's API gateway. Verified that the BOS fields
which require BOS v2 were displayed. Verified that explicitly specifying
BOS v1 worked with `sat status --bos-version v1`.## Risks and Mitigations
Low risk. The admin can always change back.
=> CRAYSAT-1700: Switch default BOS version to v2

CHANGELOG.md, sat/logging.py, tests/test_logging.py
This change adds a new logging formatter which splits each log message at each line break, and formats each line separately using the given format. Each log record is still semantically a separate log event, but the formatted output has consistent formatting across lines. This resolves an issue with the IUF omitting console log messages which did not have proper prefixes.
* Resolves [CRAYSAT-1680](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1680)
Run unit tests. Run `sat bootprep` against an invalid bootprep input file to make sure the `ERROR:` prefix is applied to each line properly.
=> CRAYSAT-1680: Format each log line separately

CHANGELOG.md, sat/cli/bootprep/input/image.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/input/test_image.py
This change adds a `wildcard` option to product-supplied images in bootprep input files. The `wildcard` option can be specified under a `base.product.filter` clause to select the base image from a product. Wildcard pattern matching is performed using standard glob syntax. See documentation of the Python `fnmatch` module for more information.
* Resolves [CRAYSAT-1697](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1697)
* `rocket`
Run unit tests. Run on a system against a simple bootprep input file with a single COS image selected using a wildcard.
=> CRAYSAT-1697: Add `wildcard` filtering option in bootprep input file

.coveragerc, .github/workflows/license-check.yaml, CHANGELOG.md, Dockerfile, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, unittest.cfg
This change modifies this repo's testing infrastructure in order to use
nose2 for running unit tests instead of nosetests. This should
future-proof our unit tests as nosetests breaks after Python 3.10 and
will not be updated to support it (the nose project is in maintenance
mode.)
This change also bumps the version of paramiko in use to 2.11.0 in order to
fix a warning about deprecated Blowfish ciphers. This was caused by an
updated version of the underlying cryptography library which added those
warnings.
* Resolves [CRAYSAT-1523](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1523)
=> CRAYSAT-1523: Update testing infrastructure to use nose2

CHANGELOG.md, sat/cli/bootsys/bos.py, tests/cli/bootsys/test_bos.py
Normally, a BOS v2 staged session will reach the state "running" when it is considered finished staging. However, if that BOS v2 staged session does not apply to any components (for example, when a limit parameter is used that does not overlap with any of the nodes in the session template), the session will go straight to "complete" instead.
Rename the `target_state` argument to the BOSV2SessionWaiter to `target_states` and change the type to a list of acceptable target states. This allows us to call it with the single state "complete" when waiting on a non-staged session and to call it with the states "complete" and "running" when waiting on a staged session.
* Resolves [CRAYSAT-1705](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1705)
* locally on macbook
* TBD
Added new unit …
=> CRAYSAT-1705: Fix logic for checking when staged BOS session is complete

CHANGELOG.md, docs/man/sat.8.rst, sat/apiclient/ims.py, sat/cli/auth/main.py, sat/cli/bootsys/state_recorder.py, sat/cli/setrev/main.py, sat/cli/showrev/system.py, sat/config.py, sat/logging.py, sat/main.py, sat/util.py, sat/warnings.py, tests/test_logging.py, tests/test_util.py
Add a new warnings.py module with a function to configure warnings.
* Uses 'once' filters and matches API gateway and S3 endpoint parameters
so that we can get one warning per host.
* Add s3.cert_verify parameter but unfortunately it needs to remain
False for now.
* Remove TODO references except in config.py where we should eventually
change the default value of s3.cert_verify.
* Add missing documentation on s3 config file section to the man page.
* I ran `sat status` with certificate verification enabled and disabled.
* I ran `sat showrev` with rgw certificate verification enabled and
disabled.
* I visually inspected the resulting warnings.
=> CRAYSAT-1310: Capture and filter InsecureRequestWarning

CHANGELOG.md, sat/apiclient/__init__.py, sat/cli/bootsys/service_activity.py, tests/cli/bootsys/test_service_activity.py
This change removes support for CRUS which is slated for removal from CSM 1.5.
* Resolves [CRAYSAT-1668](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1668)
=> CRAYSAT-1668: Remove support for CRUS

CHANGELOG.md, docker_scripts/config-docker-sat.sh
This change updates the process used to retrieve the appropriate version of kubectl to download into the container. A Python script is now used to parse out the semantic version of kubectl listed in the metal-provision repository instead of the deprecated csm-rpms repository.
* Resolves [CRAYSAT-1719](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1719)
Build cray-sat container image. Check kubectl version in image.
=> CRAYSAT-1719: Update kubectl version lookup

CHANGELOG.md
Update the changelog to pull in details about kubectl build change and cray-sat container rebuild.
=> CRAYSAT-1719: Update changelog to include build details from 3.21 release

docker_scripts/config-docker-sat.sh
Update the location of the suse.yml file in the metal-provision repository containing the kubectl version.
* Resolves [CRAYSAT-1721](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1721)
=> CRAYSAT-1721: Fix YAML file path config-docker-sat.sh script

CHANGELOG.md, sat/cli/bootsys/cabinet_power.py, tests/cli/bootsys/test_cabinet_power.py
During `sat bootsys shutdown --stage cabinet-power`, skip making a request to CAPMC and waiting on the power state of nodes when there are no non-management nodes in air-cooled cabinets to ensure are powered off. Instead, simply log an info message to that effect. Before this check, we were making a request to CAPMC to power off an empty set of xnames, which resulted in a confusing warning, and then we were waiting on a set of zero components, which also looked confusing.
Add unit tests for `do_air_cooled_cabinets_power_off`.
* Resolves [CRAYSAT-1714](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1714)
Unit tests should be sufficient here until we can do a test on a real or vshasta system.
Pretty low-risk change. Will be tested in the full context of …
=> CRAYSAT-1714: Skip CAPMC request when empty set of nodes

CHANGELOG.md, sat/hms_discovery.py, tests/test_hms_discovery.py
This change modifies the logic in the HMSDiscoveryScheduledWaiter to
check which Kubernetes jobs exist for the hms-discovery cronjob, and
checks if their creation timestamp is after the time that waiting began.
If it was, then waiting finishes; if no job is created within the
timeout duration, then the waiter will time out as normal.
A fix is also included to update the location of kubectl version in the metal-provision repo.
* Resolves [CRAYSAT-1623](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1623)
* Also resolves [CRAYSAT-1631](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1631)
Create stub version of hms-discovery cron job in minikube. Use waiter to
wait until the job is scheduled. Modify cron job such that it will never
schedule, and …
=> CRAYSAT-1623: Improve hms-discovery scheduled check

CHANGELOG.md, sat/cli/bootsys/cabinet_power.py, sat/cli/bootsys/platform.py, sat/cronjob.py, sat/hms_discovery.py, tests/cli/bootsys/test_cabinet_power.py, tests/test_cronjob.py
This change implements a feature in the cabinet power stage of power on which recreates Kubernetes cronjobs if they are not being scheduled according to their cron schedule. This is determined by checking if the cron job's last scheduled time was prior to the computed prior scheduled time based on its schedule. All cronjobs which are stuck not executing will be deleted and recreated with the same specification.
* Resolves [CRAYSAT-654](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-654)
Run unit tests. Create cron job which sleeps for longer than its cron schedule with a Forbid concurrency policy (thus causing it to frequently miss its scheduled time.) Run a simple test harness which contains the stuck cronjob check loop from the cabinet power stage …
=> CRAYSAT-654: Recreate cronjobs which are not being scheduled

CHANGELOG.md, sat/cli/bootsys/cabinet_power.py
This change removes recreating all "stuck" cronjobs from the cabinet-power stage since there was specific functionality added to recreate the hms-discovery cronjob in that stage, which would cause the cronjob to be recreated unconditionally. This removes this recreating step from cabinet-power so that the bootsys behavior is in line with docs-csm.
* Resolves [CRAYSAT-654](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-654)
=> CRAYSAT-654: Remove cronjob recreate step from cabinet-power stage

CHANGELOG.md, sat/config.py, sat/parser.py, sat/session.py, tests/common.py, tests/test_session.py
This change adds a config file option and corresponding command line option to add multitenancy support to SAT. This amounts to sending the configured tenant name as the value of the `Cray-Tenant-Name` header in each request.
* Resolves [CRAYSAT-1703](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1703)
Run `sat status --bos-fields` commands with special debug logger and inspect the headers supplied. Run unit tests.
Test script: https://gist.github.com/jack-stanek-hpe/7ab54eaa4a46e77c050d01be6db7ca1d
=> CRAYSAT-1703: Support multitenancy for SAT

CHANGELOG.md, sat/cli/bootsys/etcd.py, sat/cli/bootsys/hostkeys.py, sat/cli/bootsys/platform.py, sat/cli/bootsys/util.py, tests/cli/bootsys/test_etcd.py, tests/cli/bootsys/test_hostkeys.py, tests/cli/bootsys/test_platform.py
This change filters the known_hosts file prior to loading it into a paramiko SSHClient object in order to improve performance. Paramiko's implementation of known_hosts parsing has quadratic time complexity, which causes very poor performance in general when a large known_hosts file is used. In our particular case, it was causing additional slowdown due to the GIL since we were using the `threading` module and parsing the known hosts file several times on different threads, causing GIL thrashing.
To address this, this change pre-filters the known_hosts file to just the hosts needed in a given stage, and also changes the container stop threads to use `multiprocessing` instead, so that multiple SSH connections can occur simultaneously without compromising (as much) performance.
* Resolves …
=> CRAYSAT-1722: Speed up known_hosts loading

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
Combine https://github.com/Cray-HPE/sat/pull/136 and https://github.com/Cray-HPE/sat/pull/134 into one PR.
* Resolves [CRAYSAT-1735](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1735)
* `mug`
To quickly do a regression test of the new libraries:
* Load updated image to system, run `sat status` to check that
requests are made to the CSM APIs correctly
* In a `sat bash` session, launch a Python interpreter and use
the `sat.cli.bootsys.util.get_ssh_client()` function to test
that Paramiko clients work properly
=> CRAYSAT-1735: Bump cryptography and requests (merged dependabot PRs)

CHANGELOG.md, sat/cli/bootprep/input/session_template.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/input/test_session_template.py, tests/cli/bootprep/test_validate.py, tests/common.py
Adjust the implementation of `sat bootprep` support for multiple
architectures to match the implementation of BOS. This includes:
* Remove the ability to specify the `arch` at the top level of the BOS
session template. BOS will not support this for now.
* Change the guidance in the `sat bootprep` input file schema to say
that the BOS session template architecture values should match what
HSM returns for its components API endpoint.
* Add an enum for validation of the `arch` field in a boot set in a BOS
session template to provide clear guidance to the user when an invalid
value is used.
* Update the description of BOS's default behavior when no value is
specified for the `arch` field. It now treats this as "X86".
Update the unit tests accordingly for the above changes.
Note that …
=> CRAYSAT-1733: Adjust bootprep multi-arch feature to match BOS

CHANGELOG.md, docker_scripts/config-docker-sat.sh
Backport the change to get the `kubectl` version from the `lts/csm-1.5` branch of the `metal-provision` repo, and declare version 3.24.0.
* Resolves [CRAYSAT-1723](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1723)
* Partially resolves [CRAYSAT-1738](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1738)
=> CRAYSAT-1723, CRAYSAT-1738: Backport `lts/csm-1.5` change and declare 3.24.0 version

CHANGELOG.md, docker_scripts/config-docker-sat.sh
Use the lts/csm-1.5 branch of metal-provision so that we are using CSM 1.5's version of kubectl, and so that the integration version doesn't go past the version for 1.5.
* Resolves [CRAYSAT-1723](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1723)
Build cray-sat image.
=> CRAYSAT-1723: Use lts/csm-1.5 branch of metal-provision repository

CHANGELOG.md, docker_scripts/config-docker-sat.sh
Retrieve the kubectl version from the release/1.4 branch of csm-rpms. This should ensure that the kubectl version in the SAT container remains harmonized with the version on the NCNs on CSM 1.4 systems.
* Resolves [CRAYSAT-1723](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1723)
Build cray-sat image
=> CRAYSAT-1723: Use csm-rpms release/1.4 branch to get kubectl version

CHANGELOG.md, sat/cli/bootprep/input/configuration.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/input/test_configuration.py, tests/cli/bootprep/test_validate.py
CFS has added a new property to CFS configuration layers that allows the layer to specify whether IMS should enable DKMS support when the configuration is applied to an image during image customization. CFS added the new property `imsRequireDkms` under the new property `specialParameters` in each CFS configuration layer.
The `sat bootprep` input file schema has been updated to add a new `ims_require_dkms` property under a new `special_parameters` property under each CFS configuration layer. This maintains as much consistency as possible with CFS while adhering to the naming convention used for properties in the `sat bootprep` input file schema.
Unit tests have been modified accordingly to test this new functionality.
* Resolves [CRAYSAT-1741](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT …
=> CRAYSAT-1741: Add `sat bootprep` DKMS support

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
Update PyYAML to 6.0.1 to fix a build error. This build error was due to an incompatible change introduced in Cython 3.0. The PyYAML package has worked around this in version 6.0.1 by restricting to Cython<3.0.
Also update the pinned version of csm-api-client to 1.1.5, which relaxed the PyYAML constraint to allow versions greater than or equal to 6.0. Without this change, `pip` is unable to resolve sat's dependencies.
* Resolves [CRAYSAT-1750](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1750)
* mug
Ran the following `sat` commands to exercise relevant code:
* `sat showrev --products` (config map access)
* `sat bootprep run` (YAML loading, API access, config map access)
* `sat status` (multiple API access)
Low risk since we're just pulling in new PyYAML.
=> CRAYSAT-1750: Update PyYAML to 6.0.1

CHANGELOG.md, docs/man/sat.8.rst, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/apiclient/ims.py, sat/cli/bootprep/input/image.py, sat/cli/bootsys/k8s.py, sat/cli/bootsys/service_activity.py, sat/cli/bootsys/state_recorder.py, sat/cli/k8s/replicaset.py, sat/cli/setrev/main.py, sat/cli/showrev/system.py, sat/cli/swap/blade.py, sat/cli/swap/cable_endpoints.py, sat/config.py, sat/hms_discovery.py, sat/logging.py, sat/main.py, sat/util.py, sat/warnings.py, tests/cli/bootsys/test_k8s.py, tests/cli/bootsys/test_service_activity.py, tests/cli/bootsys/test_state_recorder.py, tests/cli/k8s/test_replicaset.py, tests/cli/showrev/test_system.py, tests/cli/swap/test_blade.py, tests/test_hms_discovery.py, tests/test_logging.py, tests/test_util.py
Backport the following fixes to release/3.21:
* CRAYSAT-1310: Capture and filter InsecureRequestWarning
* CRAYSAT-1656: Use updated load_kube_api() implementation
* CRAYSAT-1750: Update PyYAML to 6.0.1
* Bump pygments from 2.11.2 to 2.15.0
* Bump certifi from 2022.12.7 to 2023.7.22
* Bump cryptography from 41.0.0 to 41.0.3
* CRAYSAT-1751: Add changelog entry for dependabot updates
These first two changes are required to make  the PyYAML change apply cleanly. It seems like lower risk to backport those two minor changes than to try to manually resolve the merge conflicts.
* Resolves [CRAYSAT-1751](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1751)
* mug
Downloaded the cray-sat container image built from this branch and ran through `satverify.py` on mug.
Although lots of dependency …
=> CRAYSAT-1751: Resolve CVEs in cray-sat:3.21

CHANGELOG.md, docker_scripts/config-docker-sat.sh
build failure of SAT was observed due to non fetch of kube version from metal-provision repo.
Script has been updated to fetch the version from different yml file  and verified
* [Resolves [CRAYSAT-1761](https://jira-pro.it.hpe.com:8443/browse)]
need to verify the build
NA
Yet to verify the build
Low risk
=> CRAYSAT-1761: Update metal-provision file path to fix build

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
Merge two dependabot updates at once and add a changelog entry. These address vulnerabilities in the urllib3 and cryptography packages.
* Resolves [CRAYSAT-1778](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1778)
* mug
Simple smoke test performed on mug. Ran `sat status` and `sat showrev` commands.
Low risk change. Just bumps patch versions of a couple dependencies.
=> Merge dependabot updates for cryptography and urllib3

CHANGELOG.md, sat/apiclient/ims.py
When renaming images in `sat bootprep`, ensure the image architecture is retained in the new image. This field is important to IMS, so it knows how to handle any future customization operations on that image.
* Resolves [CRAYSAT-1780]()
* mug
Tested on mug by downloading the new cray-sat image, opening a shell in the container with `sat bash`, and then opening a Python interpreter and using the `copy_image` function directly to confirm that the image architecture is retained when copying an aarch64 image. Also tested on an x86_64 image for good measure.
Pretty low risk, just fixing a pretty simple bug.
=> CRAYSAT-1780: Retain image arch in `sat bootprep`

CHANGELOG.md, sat/apiclient/ims.py
Backport 3.25.6 to release/3.25 branch to get a stable build for inclusion in CSM 1.5.0 and SAT 2.6.
* Resolves [CRAYSAT-1780](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1780)
See #171
=> Backport 3.25.6 to release branch

CHANGELOG.md, Jenkinsfile.github
Change container image builds to also publish to csm-docker instead of
just sat-docker in Artifactory. Using csm-docker is more consistent with
how other CSM images are published. Publish to both locations for now to
ease the transition and to make it easier to pull in new builds of
cray-sat into CSM 1.5 patches without pulling in the related changes to
the sat-podman wrapper script.
Publishing to csm-docker has the added benefit of getting us DST image
mirroring without having to set up another mirror for sat-docker.
* Resolves [CRAYSAT-1771](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1767)
* Jenkins
Checked that Jenkins published to the correct locations in sat-docker and csm-docker.
Low risk since it just adds another publishing location.
In CSM 1.6, we will pull the cray-sat …
=> CRAYSAT-1771: Change builds to also publish to csm-docker

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/mgmt_power.py, sat/cli/bootsys/parser.py
ncn shutdown timeout is increased and hard powering off is handling taking i/p from user 
* Resolves [CRAYSAT-1513](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1513)
Yet to be testing as its need a ncn node to be brought down and verified
Yet to be performed
will update once tested
Low risk
=> CRAYSAT-1513: ncn shutdown timeout increase and hard powering off handle

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
Update the release/3.26 branch with the latest 3.26.2 from main.
* Resolves [CRAYSAT-1785](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1785)
* Resolves [CRAYSAT-1792](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1792)
* mug
Performed a smoke test of latest main branch build on mug. Ran `sat status` and `sat showrev` to check general functionality after upgrades to urllib3 and cryptography package versions.
Low risk, fixing security vulnerabilities.
=> Update release/3.26 branch with 3.26.2 version

CHANGELOG.md, sat/cli/bootprep/input/configuration.py, sat/cli/bootprep/main.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/input/test_configuration.py, tests/cli/bootprep/test_validate.py
Add support to the bootprep input file schema to support specifying `additional_inventory` when creating CFS configurations using `sat bootprep`.
This includes a schema change for the bootprep input file that allows the user to specify a new `additional_inventory` property in their CFS configuration definitions which corresponds with the field of the same name in the CFS API.
Add a unit test that just verifies that the `bootprep_schema.yaml` data file is valid against the JSON Schema metaschema. This is helpful to test only the validity of edits to the bootprep input file schema.
Add unit tests to validate against the schema new bootprep input that includes the new `additional_inventory` property.
When `additional_inventory` is specified, treat branches in the same way as for layers. That …
=> CRAYSAT-1789: Allow `additional_inventory` in bootprep CFS configs

CHANGELOG.md, sat/filtering.py, sat/logging.py, tests/test_filtering.py, tests/test_logging.py
* CRAYSAT-1800: Allow special characters in comparison RHS
Allow special characters (e.g. `-`) in the right-hand side of
comparisons in filter strings without requiring them to be contained in
double/single quotes. The only thing which should really have to be
enclosed in double/single quotes would be spaces, because those normally
indicate the end of the RHS token.
Add additional unit tests to more thoroughly test filter parsing and
behavior, including:
* A test with a filter query with `-` in the right-hand side (value) of
the comparison
* Tests with more complicated wildcards
* A test with a quoted wildcard on the right-hand side
* CRAYSAT-1800: Fix logging traceback due to deepcopy
The use of `deepcopy` in the `LineSplittingLogFormatter` causes problems
when a logging method is …
=> CRAYSAT-1800: Fix logging of filter parse errors and allow unquoted special characters in filters

CHANGELOG.md, sat/logging.py, tests/test_logging.py
The use of `deepcopy` in the `LineSplittingLogFormatter` causes problems when a logging method is called, and a format string is passed in along with an argument to be used in that format string, and the object does not support copying with `deepcopy`.
Switching to `copy` instead. This is all that is needed because the `LineSplittingLogFormatter` was just creating a copy of the log record to modify its message without modifying the original record. Using `copy` is sufficient for this purpose.
This fixes an issue seen when a filter query string could not be parsed and a logging call is made that passes along the `ParseError` object from `parsec`.
Add a unit test that ensures that the original log record's message is not indavertently changed, which is what the `deepcopy` was originally …
=> CRAYSAT-1800: Fix logging traceback due to deepcopy

CHANGELOG.md, sat/cli/swap/cable.py, sat/cli/swap/ports.py, sat/cli/swap/swap.py, sat/cli/swap/switch.py, tests/cli/swap/test_cable.py, tests/cli/swap/test_ports.py, tests/cli/swap/test_swap.py, tests/cli/swap/test_switch.py
* CRAYSAT-1798: Preserve all port policies in `sat swap`
When enabling or disabling a switch or a cable in `sat swap switch` or
`sat swap cable`, properly handle when a port has multiple port policies
applied to it. This fixes the issue where only the first port policy
associated with a port is kept through the disable/enable cycle.
The strategy for keeping a record of the port policies applied to each
port is unchanged. That is, for the disable action, for each port
policy associated with the ports to be disabled, append the
"sat-offline-" prefix to the policy name, create a new policy
with the prefixed name which has `"state": "OFFLINE"`, and then apply
the policy to the port being disabled.
Note that for ports with more than one policy associated with them (e.g.
fabric ports which have …
=> CRAYSAT-1798: Preserve all port policies in `sat swap`

CHANGELOG.md, sat/cli/swap/cable.py, sat/cli/swap/ports.py, sat/cli/swap/swap.py, sat/cli/swap/switch.py, tests/cli/swap/test_cable.py, tests/cli/swap/test_ports.py, tests/cli/swap/test_swap.py, tests/cli/swap/test_switch.py
* CRAYSAT-1798: Preserve all port policies in `sat swap`
When enabling or disabling a switch or a cable in `sat swap switch` or
`sat swap cable`, properly handle when a port has multiple port policies
applied to it. This fixes the issue where only the first port policy
associated with a port is kept through the disable/enable cycle.
The strategy for keeping a record of the port policies applied to each
port is unchanged. That is, for the disable action, for each port
policy associated with the ports to be disabled, append the
"sat-offline-" prefix to the policy name, create a new policy
with the prefixed name which has `"state": "OFFLINE"`, and then apply
the policy to the port being disabled.
Note that for ports with more than one policy associated with them (e.g.
fabric ports which have …
=>  CRAYSAT-1798: Preserve all port policies in sat swap (release/3.27)

CHANGELOG.md, sat/cli/swap/cable.py, sat/cli/swap/ports.py, sat/cli/swap/swap.py, sat/cli/swap/switch.py, tests/cli/swap/test_cable.py, tests/cli/swap/test_ports.py, tests/cli/swap/test_swap.py, tests/cli/swap/test_switch.py
* CRAYSAT-1798: Preserve all port policies in `sat swap`
When enabling or disabling a switch or a cable in `sat swap switch` or
`sat swap cable`, properly handle when a port has multiple port policies
applied to it. This fixes the issue where only the first port policy
associated with a port is kept through the disable/enable cycle.
The strategy for keeping a record of the port policies applied to each
port is unchanged. That is, for the disable action, for each port
policy associated with the ports to be disabled, append the
"sat-offline-" prefix to the policy name, create a new policy
with the prefixed name which has `"state": "OFFLINE"`, and then apply
the policy to the port being disabled.
Note that for ports with more than one policy associated with them (e.g.
fabric ports which have …
=> CRAYSAT-1798: Preserve all port policies in sat swap (release/3.25)

CHANGELOG.md, sat/cli/swap/cable.py, sat/cli/swap/ports.py, sat/cli/swap/swap.py, sat/cli/swap/switch.py, tests/cli/swap/test_cable.py, tests/cli/swap/test_ports.py, tests/cli/swap/test_swap.py, tests/cli/swap/test_switch.py
* CRAYSAT-1798: Preserve all port policies in `sat swap`
When enabling or disabling a switch or a cable in `sat swap switch` or
`sat swap cable`, properly handle when a port has multiple port policies
applied to it. This fixes the issue where only the first port policy
associated with a port is kept through the disable/enable cycle.
The strategy for keeping a record of the port policies applied to each
port is unchanged. That is, for the disable action, for each port
policy associated with the ports to be disabled, append the
"sat-offline-" prefix to the policy name, create a new policy
with the prefixed name which has `"state": "OFFLINE"`, and then apply
the policy to the port being disabled.
Note that for ports with more than one policy associated with them (e.g.
fabric ports which have …
=> CRAYSAT-1798: Preserve all port policies in `sat swap` (release/3.21)

CHANGELOG.md, sat/cli/status/status_module.py, tests/cli/status/test_status_module.py
IM:CRAYSAT-1820
Reviewer: Ryan, Shiva
_Remove unnecessary queries to BOS to get the name of the session template for every single node component in the output of sat status_
_Resolves [CRAYSAT-1820](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1820)._
_yet to be tested._
Testing on drax cluster
_After removal of additional query to BOS template, it not impacts the original output of `sat status`._
_Low Risk_
=> CRAYSAT-1820: Remove unnecessary queries

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/mgmt_power.py, sat/cli/bootsys/platform.py, tests/cli/bootsys/test_platform.py
IM:CRAYSAT-1621
Reviewer:Ryan
The changes have be made on two stages of bootsys: 
**1. sat bootsys shutdown -- platform-services**
freeze ceph has been cleaned from the this stage.
**2. sat bootsys shutdown -- ncn-power:** 
Here we have modified the way shutdown of the ncn's are performed.
Earlier all the ncn's except m001 would be shutdown simultaneously together. Now it would be performed in grouping.
And the order would be workers, masters(except m001), unmap rbd on m001, freeze ceph and then shutdown the storage nodes.
The changes are in initial stage, may need add on's post review.
* Resolves [CRAYSAT-1621](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1621)
* Future …
=> CRAYSAT-1621: modifying sat bootsys shutdown approach

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, sat/cli/status/status_module.py, tests/cli/status/test_status_module.py
IM:CRAYSAT-1824
Reviewer:Ryan
This will Backport cray-sat 3.27.4 through 3.27.9
- Update the version of jinja2 from 3.0.3 to 3.1.3
- Update the version of cryptography from 41.0.6 to 42.0.0
- Remove unnecessary queries to BOS to get the name of the session template for every single node component in the output of sat status
- Changed the WARNING messages about the deleted BOS sessions to DEBUG messages for sat status
- Changed the "Most Recent Image" column to show the IMS image ID instead of image name for sat status
- Update the version of cryptography from 42.0.0 to 42.0.2
- Update the version of cryptography from 42.0.2 to 42.0.4
[CRAYSAT-1816](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1816)
[CRAYSAT-1819](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1819) …
=> CRAYSAT-1824:Backport cray-sat 3.27.4 through 3.27.9

CHANGELOG.md, docs/man/sat-showrev.8.rst, sat/cli/showrev/main.py, sat/cli/showrev/products.py, tests/cli/showrev/test_products.py
IM: CRAYSAT-1763
Reviewer: Ryan
_From this PR, will stop supporting `--release-files` option in `sat showrev`_
_[CRAYSAT-1763](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1763)_
_baldar_
_Tested with `sat showrev` commands. Test went fine without any issues_
_Low Risk_
=> CRAYSAT-1763: Stop supporting --release-files option in sat showrev

CHANGELOG.md, sat/apiclient/pcs.py, sat/cli/bootsys/cabinet_power.py, sat/cli/bootsys/parser.py, sat/cli/bootsys/power.py, sat/cli/swap/blade.py, tests/apiclient/test_pcs.py, tests/cli/bootsys/test_cabinet_power.py, tests/cli/bootsys/test_power.py, tests/cli/bootsys/test_service_activity.py, tests/cli/swap/test_blade.py
Replace calls to the CAPMC API with equivalent calls to the PCS API.
I tried to keep the software API of `PCSClient` mostly compatible with `CAPMCClient`, though there may be differences that aren't covered in the tests.
This hasn't been tested on a real system with PCS installed yet.
* Resolves [CRAYSAT-956](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-956)
=> CRAYSAT-956: Replace CAPMC calls with PCS calls

CHANGELOG.md, sat/hms_discovery.py
Reviewer:Ryan
need to increase the grace period to allow more time for a new job to be scheduled by the cronjob. 
It might be good to wait a 3 extra minutes, which is the interval on which the job is created by the cronjob.
Hence increasing the grace period.
* Resolves [CRAYSAT-1835](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1835)
yet to be tested
Baldar
minimal
=> CRAYSAT-1835:increasing default grace period for hsm discovery

CHANGELOG.md, sat/cli/bmccreds/constants.py, sat/cli/bmccreds/creds_manager.py, sat/cli/bmccreds/main.py, sat/cli/bmccreds/parser.py, tests/cli/bmccreds/test_creds_manager.py, tests/cli/bmccreds/test_main.py
IM:CRAYSAT-1826
Reviewer: Ryan
_Improve "sat bmccreds" to accept and generate stronger passwords_
_[CRAYSAT-1826](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1826)_
_baldar and odin_
_Test went fine when executed `sat bmccreds` with `--ranom-password` with all the test cases_
_Minimal_
=> CRAYSAT-1826: Allow for more complex passwords in `sat bmccreds`

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/input/image.py
Incorrect logging is observed in sat bootprep logs SAT is also generating a session name, 
which is conflicting with session name generated in create_image_customization_session
Hence updating the `begin_image_configure` to pass session name to address sat bootprep incorrect logging
* Resolves [CRAYSAT-1747](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1747)
Tested
baldar
sat bootprep run test was verified to check the session name being logged.
**Before changes:**
ncn-m001:/etc/cray/upgrade/csm/media/230912-2 # sat bootprep run  --limit images --limit configurations --vars-file session_vars.yaml --format json --bos-version v2 .bootprep-230912/management-bootprep-shiva.yaml …
=> CRAYSAT-1747: Allow passing CFS session name

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
IM:CRAYSAT-1775
Reviewer:Ryan
Update the _update_container_status method of the CFSImageConfigurationSession class in csm_api_client.service.cfs to handle the case when either init_container_statuses or container_statuses or both are None.
_Update the update_container_status method of the CFSImageConfigurationSession class in csm_api_client.service.cfs when either init_container_statuses or container_statuses or both are None.
If they are None we can log an info message and will skip processing the container statuses until they are populated._
_Resolves [CRAYSAT-1775](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1775)._
Odin
_Test went fine with bootprep command without hitting any issues_
_Minimal_
=> CRAYSAT-1775:Update container status in csm_api_client.service.cfs

CHANGELOG.md, sat/cli/bootprep/documentation.py
IM:CRAYSAT-1777
Reviewer:Ryan
_Update `generate_docs_tarball` to pass the correct log message in `sat bootprep generate-docs` to output the relative path as given by the user with the `-o OUTPUT_DIR` option._
_Resolves CRAYSAT-1777 ._
_Odin_
_Test went fine for all the possible cases with `sat bootprep generate-docs` command including `-o` option_
_Minimal_
=> CRAYSAT-1777: Correct file path for `sat bootprep generate-docs`

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
IM:CRAYSAT-1837
Reviewer:Ryan
python-csm-api-client builds were taking approximately 35 mins to complete the build.
Will improvise it to take less amount of time by adding poetry.lock file that resolves the dependencies
_python-csm-api-client builds are taking 35 minutes_
To improvise the build to take less amount of time, we added the poetry.lock file which is an auto generated script from Poetry 1.5.1
poetry.lock file already has its transitive dependencies.
As we added poetry.lock file Jenkins does not need to resolve its dependencies, which takes a minimal amount of time.
_Resolves [CRAYSAT-1837](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1837)._
_Will observe the Jenkins build pipeline of `python-csm-api-client`._
_It …
=> CRAYSAT-1837: Improve python-csm-api-client build

CHANGELOG.md, docs/man/sat-swap.8.rst, docs/man/sat-switch.8.rst, sat/cli/swap/main.py, sat/cli/switch/main.py, tests/cli/swap/test_main.py, tests/cli/switch/test_switch.py, tests/test_util.py
Deprecate the `sat swap switch` and `sat swap cable` commands and refer the user to the Slingshot Operations Guide for information on the Orchestrated Maintenance feature instead.
For now, this is only a deprecation and a prompt, but the user can still continue with `sat swap switch/cable` if they want. In the future, we will remove the ability to continue with the logic in `sat swap` and just log the deprecation message as an error or remove the command entirely.
Also log the same warning for the `sat switch` command which was just an alias for `sat swap switch`.
* Resolves CRAYSAT-1799
Tested running `sat swap switch`, `sat swap cable`, and `sat switch` in a local virtual environment and confirmed that the appropriate messages were logged and the prompt …
=> CRAYSAT-1799: Deprecate `sat swap switch/cable`

CHANGELOG.md, docs/man/sat-bmccreds.8.rst
IM:CRAYSAT-1838
Reviewer:Ryan
This change adds additional parameters to `sat bmccreds` in sat-bmccreds(8) man page.
Build docs with `make` and inspect for formatting and content.
_Update man page for "sat bmccreds" to mention new password generation options_
_Resolves [CRAYSAT-1838](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1838)._
_Baldar_
_Execution of `sat-man bmccreds` to check all the contents displayed in format._
_NA_
=> CRAYSAT-1838: Update sat-bmccreds(8) man page

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py, sat/cli/bootsys/platform.py
Reviewer: Ryan
- sat bootsys boot platform-services: removed the unfreeze ceph from this stage.
- sat bootsys boot ncn-power: modifying the boot order of groups from manager,storage and worker to storage, unfreezing ceph , manager and then the worker nodes
* Resolves [CRAYSAT-1707](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1707)
`
Yet to be tested 
yet to be tested 
need to power off and then power on the cluster to check the changes
minimal
=> CRAYSAT-1707: sat bootsys boot stages modification.

CHANGELOG.md, sat/cli/bootsys/platform.py
Reviewer:Ryan
- Addressing the bug were the retries are instantaneous instead of waiting for sleep time before next attempt.
- Adding the import to get the time.sleep effective before next attempt to recreate cron jobs.
* Resolves [CRAYSAT-1839](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1839)
Tested.
* `<fanta>`
Tried to poweroff and power on the nodes and see if the issue gets fixed without the traceback error.
Able to get the traceback fixed in the o/p attached below
minimal
=> CRAYSAT-1839: Fixing the bug by importing time to handle sleep time

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
The version of the Python kubernetes client package was ahead of the
version of Kubernetes running in CSM 1.5, which resulted in some
compatibility issues. For example, `CoreV1Api.list_node` did not work if
a condition with a type of "ReadonlyFilesystem" was present on any of
the Kubernetes nodes in the cluster.
See https://github.com/kubernetes-client/python?tab=readme-ov-file#compatibility
for details on the compatibility of the Python `kubernetes` package with
the Kubernetes cluster version.
Also update the version of csm-api-client, which has been updated to
relax the kubernetes version constraint and allow versions >= 22.0
rather than only >= 23.0.
* Resolves CRAYSAT-1848
* Merge after https://github.com/Cray-HPE/python-csm-api-client/pull/28
* odin
Built the container image, …
=> CRAYSAT-1839: Fix kubernetes version to match version in CSM

CHANGELOG.md, docs/man/sat-firmware.8.rst, sat/apiclient/fas.py, sat/cli/firmware/main.py, sat/cli/firmware/parser.py, tests/apiclient/test_fas.py, tests/cli/firmware/test_firmware.py
IM: CRAYSAT-1193
Reviewer: Ryan
Improved snapshot creation by removing expiration time 
Add delete option to prompt user to delete the snapshot if it is no longer needed.
- Polling the snapshot in `sat firmware` resulted in HTTP errors in large clusters.
Hence, adding the retry option when it consecutively fails for up to 5 times.
- Remove expiration time and add `--delete-snapshot` option to prompt the user to delete the snapshot
if it is no longer needed. By default, log a message referring the user how to delete the snapshot.
_Resolves [CRAYSAT-1193](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1193)._
Baldar
_Test by creating a new snapshot using `sat firmware` command_
_Test by deleting the snapshot using `sat firmware …
=> CRAYSAT-1193:Improve create and delete fas snapshot

CHANGELOG.md, sat/cli/bootsys/k8s.py, sat/cli/bootsys/platform.py
Updating the sat bootsys kubelet start function to address chronjob creation failure
IM:CRAYSAT-1839
Reviewer:Ryan
modified the do_kubelet_start function to add the wait after kubelet gets started.
using the Waiter class that is already used in this module. Created a new Waiter subclass that implements the has_completed method to query the Kubernetes API to get the nodes in the Cluster.
Once the query returns successfully, would be proceeding with the next step.
* Resolves [CRAYSAT-1839](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1839)
Yet to be tested .
YTT
will power off the nodes and power on the node to validate the functionality inclusion during the power on.
Minimal
=> CRAYSAT-1839-sat-bootsys-waiter-subclass-addition

CHANGELOG.md, docs/man/sat-hwinv.8.rst, sat/cli/hwinv/parser.py, sat/system/cabinet_pdu.py, sat/system/cabinet_pdu_power_connector.py, sat/system/component.py, sat/system/constants.py, sat/system/mgmt_switch.py, sat/system/node_bmc.py, sat/system/router_bmc.py, sat/system/system.py, tests/system/component_data.py, tests/system/test_cabinet_pdu.py, tests/system/test_cabinet_pdu_power_connector.py, tests/system/test_mgmt_switch.py, tests/system/test_node_bmc.py, tests/system/test_router_bmc.py
IM: CRAYSAT-1138
Reviewer: Ryan
Add new HSM types, namely `NodeBMC`, `RouterBMC`, `MgmtSwitch`, `CabinetPDU` and `CabinetPDUPowerConnector` to `sat hwinv`
_This PR is to add new HSM types, namely `NodeBMC`, `RouterBMC`, `MgmtSwitch`, `CabinetPDU` and `CabinetPDUPowerConnector` to `sat hwinv`_
_Resolves [CRAYSAT-1138](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1138)._
_Odin_
_Test the `sat hwinv` command with newly added parameters for all the new components_
_N/A_
=> CRAYSAT-1138: Add new HSM types to `sat hwinv`

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py
IM:CRAYSAT-1582
Reviewer:Ryan
Adding a function to mount ceph and s3fs after checking the ceph health in ncn power stage
* Resolves [CRAYSAT-1582](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1582)
* Tested on surtur and fanta system
Ncn's were powered off and then powered on to validate the changes.
In the step: sat bootsys boot --stage ncn-power --ncn-boot-timeout 900
The output was observed during the process of above command.Once the Ceph was …
=> Adding func to mount ceph/s3fs in ncn-power stage

.github/workflows/license-check.yaml, CHANGELOG.md, docs/man/sat-firmware.8.rst, sat/apiclient/fas.py, sat/cli/firmware/main.py, sat/cli/firmware/parser.py, tests/apiclient/test_fas.py, tests/cli/firmware/test_firmware.py
IM: CRAYSAT-1868
Reviewer: Ryan
Backporting to include:
Improved snapshot creation by removing expiration time Add delete option to prompt user to delete the snapshot if it is no longer needed.
(cherry picked from commit 1700360b92cf6805b2f1e38fe00298959727419e)
- Polling the snapshot in `sat firmware` resulted in HTTP errors in large clusters.
Hence, adding the retry option when it consecutively fails for up to 5 times.
- Remove expiration time and add `--delete-snapshot` option to prompt the user to delete the snapshot
if it is no longer needed. By default, log a message referring the user how to delete the snapshot.
Resolves …
=> CRAYSAT-1868: Backport of `sat firmware`

.github/workflows/license-check.yaml, CHANGELOG.md, docs/man/sat-firmware.8.rst, sat/apiclient/fas.py, sat/cli/firmware/main.py, sat/cli/firmware/parser.py, tests/apiclient/test_fas.py, tests/cli/firmware/test_firmware.py
IM: CRAYSAT-1868
Reviewer: Ryan
Backporting to include:
Improved snapshot creation by removing expiration time Add delete option to prompt user to delete the snapshot if it is no longer needed.
- Polling the snapshot in `sat firmware` resulted in HTTP errors in large clusters.
Hence, adding the retry option when it consecutively fails for up to 5 times.
- Remove expiration time and add `--delete-snapshot` option to prompt the user to delete the snapshot
if it is no longer needed. By default, log a message referring the user how to delete the snapshot.
Resolves [CRAYSAT-1868](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1868)
_List the environments in which these changes …
=> CRAYSAT-1868:Backport of `sat firmware`

CHANGELOG.md, sat/cli/bootsys/platform.py, tests/cli/bootsys/test_platform.py
IM:CRAYSAT-1100
Reviewer:Ryan
Implementation to improve `sat bootsys shutdown --stage platform-services` which is in progress.
_Improve `sat bootsys shutdown --stage platform-services`_
- Change the -n 3 to -n 1 in the xargs command used to stop containers running under containerd.
- If containers fail to stop, automate the procedure of trying to stop them again.
_Resolves [CRAYSAT-1100](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1100)_
_fanta_
Capture the …
=> CRAYSAT-1100:Improve sat bootsys platform-services

CHANGELOG.md, sat/cli/bootsys/bos.py, tests/cli/bootsys/test_bos.py
IM:CRAYSAT-1869
Reviewer:Ryan
There is a rounding error when SAT reports status on percentage done. It rounds up to 100% when the actual number reported by BOS is something like 99.9475. For anything other than 100%, most people would not care. But 100% means it is all done, so why would SAT still be waiting for it to go over 100%
Hence, Updating the rounding to 2 decimal places instead of no decimal places and then not rounding if the value above 99 to address the bug and showing upto 10 decimal places.
The same case is added part of the unit test for the class.
* Resolves [CRAYSAT-1869](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1869)
_List the environments in which …
=> CRAYSAT-1869: Addressing the value rounding bug

CHANGELOG.md, sat/cli/status/status_module.py
The `SLSStatusModule` used by `sat status` has only `Node` as its `component_types`, meaning information from SLS is only added for nodes. The query, however, obtains SLS data for all components known to SLS. Modify this query to use the `/search/hardware` endpoint of SLS with `type=comptype_node` as a query parameter to limit the results to only the node components.
* Resolves CRAYSAT-1871
* Local virtual environment against drax
Ran `sat status` from my macbook against drax with debug logging enabled to verify API requests made. Executed with multiple option combinations, including:
* `--types Node`
* `--types NodeBMC`
* `--types Node NodeBMC`
* `--types all`
* Same as above but with addition of `--sls-fields` option
This is pretty low-risk. The data format returned by the two SLS API …
=> CRAYSAT-1871: Limit SLS query in `sat status` to only Nodes

CHANGELOG.md, sat/cli/status/main.py, sat/cli/status/status_module.py, tests/cli/status/test_status_module.py
Backport the following changes to release/3.21 for inclusion in CSM 1.4 and SAT 2.5.
* #221 
* #228 
* Resolves CRAYSAT-1866
* Resolves CRAYSAT-1871
See linked PRs above.
See linked PRs above.
=> CRAYSAT-1866, CRAYSAT-1871: Backport `sat status` fixes to release/3.21 for CSM 1.4 and SAT 2.5

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
_Combines https://github.com/Cray-HPE/sat/pull/233 and https://github.com/Cray-HPE/sat/pull/226 from dependabot into a single PR with a changelog update._
_Resolves 2 dependabot alerts in [CRAYSAT-1870](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1870)._
_Baldar_
_Basic testing of  `sat` commands which uses `requests` and `urllib`_
_N/A_
=> Craysat 1870 dependabot security updates

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
Update the _update_container_status method of the CFSImageConfigurationSession class in csm_api_client.service.cfs to handle the case when either init_container_statuses or container_statuses or both are None.
(cherry picked from commit dc5b6ae4bff1cbe7ac25df1ed30c188e03f2e517)
_Backport the following changes to release/3.25 for inclusion in CSM 1.5 and SAT 2.6._
- https://github.com/Cray-HPE/sat/pull/205
Resolves [CRAYSAT-1876](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1876)
Baldar
Sanity tested on baldar
_Low_
=> CRAYSAT-1876: Backport cfs fixes to release/3.25 for CSM 1.5 and SAT 2.6

CHANGELOG.md, sat/cli/bootsys/ceph.py, tests/cli/bootsys/test_ceph.py
IM:CRAYSAT-1581
Reviewer:Ryan
During the ceph health validation,in ncn-power stage.PG_NOT_DEEP_SCRUBBED check would be in health_warn status and that would abort the next steps following ceph health check as pgs not deep-scrubbed in time. Since it can be ignored, we are adding it to the acceptable checkswhich can be not considered while returning the ceph health.
* Resolves [CRAYSAT-1581](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1581)
* Yet to be tested
Will have power on and power off the ncn's. To validate the changes and see how it behaves during the ceph health check.
minimal
=> CRAYSAT-1581: Updating acceptable checks in ceph health validation stage

CHANGELOG.md, sat/cli/bootsys/cron.py, sat/cli/bootsys/filesystems.py, sat/cli/bootsys/mgmt_power.py, tests/cli/bootsys/test_cron.py, tests/cli/bootsys/test_filesystems.py, tests/cli/bootsys/test_mgmt_power.py
Unmount filesystems of type `ceph` and `fuse.s3fs` on ncn-m001 when shutting down. Also do the same for any filesystems mounted from RBD devices.
Add an activity check that uses `lsof` to check if filesystems can be unmounted or if there are active processes using them, and report these to the admin, so they can stop the offending processes as appropriate.
Disable the cron job that automatically mounts Ceph and s3fs filesystems on ncn-m001, so that they won't get remounted before the node is shut down. Re-enable it at the appropriate time during the power on.
* Resolves CRAYSAT-1861
* Resolves CRAYSAT-1872
* fanta
Minimal testing so far. Just tested the functions on their own to limit system disruption.
Still need to test full-system power down.
Adds a significant amount of code and …
=> CRAYSAT-1861: Unmount Ceph and s3fs filesystems on ncn-m001 during shutdown

CHANGELOG.md, sat/cli/bootsys/bos.py
If `sat bootsys` fails to create a BOS session for a BOS session template, it will still attempt to check the status of a non-existent BOS session, which results in a `TypeError` traceback when attempting to get information about a BOS session with `None` as its ID.
* Resolves CRAYSAT-1859
* rocket
Tested on rocket by passing in a non-existent BOS session template to `sat bootsys boot --stage bos-operations`. Tested with and without this fix to see the difference. With this fix, a traceback no longer occurs.
Tested also with a valid BOS session template to ensure it still works as it should, waiting on the BOS session which is created.
See output in comments.
This is a pretty low-risk change as it only affects whether we attempt to wait on failed BOS sessions and re-orders an info log …
=> CRAYSAT-1859: Improve BOS failure handling in `sat bootsys`

.github/workflows/backport.yaml
Add the backport action, so that we can more easily backport changes to older release branches with a comment in the pull request of the form:
```
/backport BRANCH_NAME
```
where `BRANCH_NAME` is the name of the branch to which the PR should be backported.
* Implemented to support easier backport of CRAYSAT-1859
I'm not sure if this can be tested until the GitHub Actions workflow is actually defined in the main branch of the repository.
Low risk. This just implements a new action on the repo for backporting.
=> CRAYSAT-1859: Add backport action

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py, tests/cli/bootsys/test_mgmt_power.py
IM:CRAYSAT-1817
Reviewer: Ryan
_Automate the procedure of setting the next boot device to disk before the management nodes are powered off as part of the full-system shutdown._
[CRAYSAT-1817](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1817)
Rocket
Will do full system shutdown and boot to see the behavior of boot order
_Minimal_
=> CRAYSAT-1817: Automate procedure of setting next boot device to disk

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py
IM:CRAYSAT-1787
Reviewer:Ryan
Adding ceph health check bypass prompt for the user to decide whether to wait or proceed with skipping the health check after unfreezing of ceph is done. As it may take some time and the next steps may not explicitly require, by the time it comes back it would be good to use.
* Resolves [CRAYSAT-1787](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1787)
Tested on Rocket system
Will have to power off and power on the ncn's to verify how the unfreeze ceph and ceph health check bypass works during ncn-power stage of sat bootsys
minimal
=> CRAYSAT-1787: Adding ceph health check bypass in sat bootsys ncn-power

CHANGELOG.md, sat/cli/bootsys/cabinet_power.py, sat/cli/bootsys/platform.py, sat/cronjob.py, sat/hms_discovery.py, tests/test_hms_discovery.py
Remove the step that automatically checks for and re-creates stuck
Kubernetes CronJobs from the `platform-services` stage of `sat bootsys
boot`. This should not be necessary anymore starting in Kubernetes 1.21,
which made a new CronJobControllerV2 the default.
In addition, improve the logic of the HMSDiscoveryScheduledWaiter, so
that it will more reliably detect when an `hms-discovery` Job has been
scheduled for the CronJob. Pass in an explicit `start_time`, so that we
can look for any jobs created for the CronJob after it is re-enabled.
This ensures we won't miss the first one, which could be scheduled
between when we set `suspend=False` on the CronJob and when we create
the `HMSDiscoveryScheduledWaiter`.
* Resolves CRAYSAT-1878
* rocket
Tested on rocket as follows:
* Suspended the …
=> CRAYSAT-1878: Remove automatic cronjob recreation from `bootsys`

CHANGELOG.md, sat/cli/bootsys/util.py, tests/cli/bootsys/test_util.py
IM:CRAYSAT-1860
Reviewer:Ryan
Change the missing host key policy used with Paramiko in sat bootsys to the AutoAddPolicy to reduce warning messages displayed to the user.It will silence the warnings and auto-add every key it encounters for a host it doesn't have a known hosts entry for yet.
* Resolves [CRAYSAT-1860](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1860)
Yet to be tested
minimal
=> CRAYSAT-1860:Handling sat bootsys stage platform-services paramiko SSH warnings

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py
_Automate the steps to recreate the /var/opt/cray/sdu/collection symbolic link to point at the collection-mount location where the fuse.s3fs filesystem is mounted._
_Restarting cray-sdu-rda is one of the way to fix the symbolic link when it points at the local directory, collection-local, instead of the s3fs mount, collection-mount on ncn-m001_
_[CRAYSAT-1865](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1865)_
Rocket
Tested whether /var/opt/cray/sdu/collection symbolic link point at the collection-mount location where the fuse.s3fs filesystem is mounted
Tested for different …
=> CRAYSAT-1865: Recreate SDU collection link

CHANGELOG.md, sat/waiting.py
The `LOGGER` was incorrectly created with `__file__` as the logger name instead of `__name__`. As a result, it was not included under the `sat` package logger's hierarchy, and the expected log handlers were not applied to messages logged by this module. Fix this by specifying `__name__` instead, so the logger has the name `sat.waiting`, which is under the `sat` logger.
* Resolves CRAYSAT-1890
* rocket
Ran `sat bootsys shutdown --stage capture-state` followed by `sat
bootsys boot --stage k8s-check --k8s-timeout 10` to force a
`Waiter` subclass to timeout, so I could observe the error log message.
As expected, it timed out waiting on new pods that were created by K8s
Jobs to reach a running or completed state, and it emitted the correctly
formatted log message of the form:
```
ERROR: …
```
=> CRAYSAT-1890: Fix `sat.waiting` logger

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py
_Modify `sat bootsys boot --stage ncn-power` to boot the master nodes (other than ncn-m001) and the worker nodes at the same time._
_Resolves [CRAYSAT-1888](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1888)._
Rocket
_Will test `sat bootsys boot --stage ncn-power` which should boot masters and worker nodes simultaneously. In turn, it should take less time to complete this stage._
_Low risk as we only booting the worker and masters parallelly_
=> CRAYSAT-1888: Boot Kubernetes master and worker nodes simultaneously

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/input/image.py
* CRAYSAT-1330: Specify image name directly in CFS session when possible
When possible, specify the desired resulting image name directly when
creating the CFS session instead of requiring a costly and failure-prone
image rename operation after the CFS configuration has been completed.
This greatly improves the reliability and performance of `sat bootprep`
for image customization.
Not tested yet.
* CRAYSAT-1330: Update to version 2.0.0 of csm-api-client
Version 2.0.0 of `csm-api-client` introduces the ability to specify the
name of images when images are customized in CFS.
* Resolves CRAYSAT-1330
* Requires merge of Cray-HPE/python-csm-api-client#30
* rocket
Created a build of the sat container image and tested as follows:
Created a bootprep file that builds and …
=> CRAYSAT-1330: Specify image name directly in CFS session when possible

CHANGELOG.md, sat/main.py
During the sat status execution if the user token is expired, there is a traceback which comes as the output. Hence graceful handling of the token expiry is added to inform the user.
* Resolves [CRAYSAT-1392](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1392)
* rocket
Manually the expiry date was updated in ~/.config/sat/tokens/api_gw_service_nmn_local.vers.json to replicate the issue.
And then the sat commands such as sat status, hwinv, hwmatch were executed to validate the changes
Low risk
=> CRAYSAT-1392: Graceful handle of user token expiry

CHANGELOG.md, sat/apiclient/bos.py, sat/cli/bootsys/bos.py, tests/cli/bootsys/test_bos.py
_Backport cray-sat 3.30.1 through 3.30.2_
* Resolves [CRAYSAT-1706](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1706): https://github.com/Cray-HPE/sat/pull/255
#drax
_See the linked PR_
_See the linked PR_
=> CRAYSAT-1706: To stop waiting if BOS session is deleted 

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
Updating cray-product-catalog & csm-api-client to latest versions
* Resolves [CRAYSAT-1884](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1884)
* Rocket,Gamora,Surtur
Test the below SAT utilities
sat showrev --products
sat bootprep
cfs-config-util
Minimal
=> CRAYSAT-1884: Updating cray-product-catalog & csm-api-client to latest versions

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/bos.py, sat/cli/bootsys/parser.py, sat/config.py
_Changed `sat bootsys` to enable default timeouts to infinite for BOS boot, shutdown, and reboot._
_Updated the man page appropriately_
_Resolves [CRAYSAT-1893](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1893)._
* drax
_Will test by doing shutdown, boot and reboot of `bos-operations` stage with and without timeout options_
_Minimal_
=> CRAYSAT-1893: Make default BOS timeouts infinite

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/bos.py, sat/cli/bootsys/parser.py, sat/config.py
_Changed sat bootsys to enable default timeouts to infinite for BOS boot, shutdown, and reboot._
_Updated the man page appropriately_
- Resolves [CRAYSAT-1893](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1893): https://github.com/Cray-HPE/sat/pull/259.
See the linked PR
See the linked PR
=> CRAYSAT-1893: Backport to 3.31.1

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/status/parser.py, sat/cli/status/status_module.py, sat/config.py, tests/test_config.py
_Update sat to use the new version of `csm-api-client` implemented in [CRAYSAT-1840](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1840)_
- _Update the `sat status` to support both cfs v2 and v3_
_Resolves [CRAYSAT-1841](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1841)._
drax
_Test the `sat status` with cfs v2 and v3 and without cfs field to test the default._
_Possibly will try to change the page size and test cfs v3_
_Risks might be depend on cfs v3 introduction_
=> CRAYSAT-1841: Update sat status to support CFS v2 or v3

CHANGELOG.md, sat/apiclient/__init__.py, sat/cli/bootprep/image.py, sat/cli/bootprep/input/configuration.py, sat/cli/bootprep/input/image.py, sat/cli/bootprep/input/instance.py, sat/cli/bootprep/input/session_template.py, sat/cli/bootprep/main.py, sat/cli/bootsys/service_activity.py, tests/cli/bootprep/input/test_configuration.py, tests/cli/bootprep/input/test_image.py, tests/cli/bootprep/test_main.py, tests/cli/bootsys/test_service_activity.py
_Update `sat bootprep` and `sat bootsys` to use cfs v2 and should not break any changes._
- Resolves [CRAYSAT-1902](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1902)
drax
_Test with `sat bootprep` where the CFS configurations get created and can validate `session_checks` for service_acitivity of `sat bootsys`._
_Minimal_
=> CRAYSAT-1902: Update `sat bootprep` with new changes of cfs v2

CHANGELOG.md, sat/apiclient/__init__.py, sat/cli/bootprep/image.py, sat/cli/bootprep/input/configuration.py, sat/cli/bootprep/input/image.py, sat/cli/bootprep/input/instance.py, sat/cli/bootprep/input/session_template.py, sat/cli/bootprep/main.py, sat/cli/bootsys/service_activity.py, tests/cli/bootprep/input/test_configuration.py, tests/cli/bootprep/input/test_image.py, tests/cli/bootprep/test_main.py, tests/cli/bootsys/test_service_activity.py
_Backport sat container through 3.32.1_
_Resolves [CRAYSAT-1902](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1902): https://github.com/Cray-HPE/sat/pull/264._
_See the linked PR._
_See the linked PR_
=> CRAYSAT-1902: Backport to 3.32.1

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
_update-cfs-config and prepare-images stage is failing after hanging during CSM only upgrade using IUF_
_It hangs up when its executing the command "git ls-remote https://crayvcs@api-gw-service-nmn.local/vcs/cray/uss-config-management.git "_
_Tried fetching the credentials from container if present else kubernetes which doesn't get hungs up for long time_
_Resolves [CASMTRIAGE-7272](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7272)_
- Fix from csm-api-client: https://github.com/Cray-HPE/python-csm-api-client/pull/40
fanta
_Tested with IUF which is working without hangs up_
_Minimal_
=> CASMTRIAGE-7272: update-cfs-config and prepare-images stage is failing after hanging during CSM only upgrade using IUF

CHANGELOG.md, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/session_template.py, tests/cli/bootprep/input/test_session_template.py
Reviewer: Annapoorna
In order to suport iSCSI in CSM 1.6. jinja rendering of the rootfs_provider_passthrough value is necessary. Hence the functionality to render the value has been added. 
For both UAN & Compute support has been added for the input yaml to be handled.
* Resolves [CRAYSAT-1900](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1900)
* `<Gamora>`
The modified input yaml file consisting of both iSCSI and DVS was considered for testing sat bootprep to create the session templates. It successfully was able to create all the type of templates.
minimal
=> CASMTRIAGE-1900: Add jinja render to rootfs_provider_passthrough to support iSCSI

CHANGELOG.md, docs/man/sat-bootprep.8.rst, docs/man/sat-bootsys.8.rst, docs/man/sat-status.8.rst, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/session_template.py, tests/cli/bootprep/input/test_session_template.py
_Backport the sat container to 3.32.4_
_This backports the following fixes._
1. [CASMTRIAGE-7272](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7272):
-  https://github.com/Cray-HPE/python-csm-api-client/pull/40
-  https://github.com/Cray-HPE/sat/pull/267
2. [CRAYSAT-1843](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1843), [CRAYSAT-1899](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1899): 
- https://github.com/Cray-HPE/sat/pull/268
3. [CRAYSAT-1900](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1900): https://github.com/Cray-HPE/sat/pull/265
_See the linked PRS._
_See the linked PRs_
=> Backport sat-container to 3.32.4

CHANGELOG.md, Dockerfile, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
_Update the version of the Python kubernetes client package which compatible to the version of Kubernetes running in CSM 1.6_
_Also update the version of csm-api-client, which has been updated along with the kubernetes version_
* Resolves [CRAYSAT-1849](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1849)
* Merge after https://github.com/Cray-HPE/python-csm-api-client/pull/42
starlord
_Built the container image, downloaded to odin, and ran the
CoreV1Api.list_node method in a Python interpreter in the sat bash
shell._
_This should be low risk. It is aligning the version of the kubernetes Python package with the …
=> CRAYSAT-1849: Update Python k8s version to the latest one supported in CSM 1.6

CHANGELOG.md, Dockerfile, Jenkinsfile.github, Makefile, docker_scripts/config-docker-sat.sh
Update the cray-sat image build process to get the Kubernetes version from its new location in the node-images repository instead of the old version in the deprecated metal-provision repository.
This is more involved than just changing the repository URL and path in the `docker_scripts/config-docker-sat.sh` script because the node-images repository is private in GitHub, but metal-provision was public. Thus we need to authenticate to GitHub when cloning this repository. This is best achieved through a `git` command in the Jenkinsfile.
In order to continue supporting local builds, add a target to the `Makefile` that clones the node-images repository if it does not already exist. Use the `git` protocol instead of `https` to allow it to use the user's configured SSH keypair to authenticate …
=> CRAYSAT-1912: Get K8s version from node-images

CHANGELOG.md, Dockerfile, Jenkinsfile.github, Makefile, docker_scripts/config-docker-sat.sh
Update the cray-sat image build process to get the Kubernetes version from its new location in the node-images repository instead of the old version in the deprecated metal-provision repository.
This is more involved than just changing the repository URL and path in the `docker_scripts/config-docker-sat.sh` script because the node-images repository is private in GitHub, but metal-provision was public. Thus we need to authenticate to GitHub when cloning this repository. This is best achieved through a `git` command in the Jenkinsfile.
In order to continue supporting local builds, add a target to the `Makefile` that clones the node-images repository if it does not already exist. Use the `git` protocol instead of `https` to allow it to use the user's configured SSH keypair to authenticate …
=> CRAYSAT-1912: Get K8s version from node-images (#273)

CHANGELOG.md, docs/man/sat-bmccreds.8.rst, sat/cli/bmccreds/constants.py, sat/cli/bmccreds/creds_manager.py, sat/cli/bmccreds/main.py, sat/cli/bmccreds/parser.py, tests/cli/bmccreds/test_creds_manager.py, tests/cli/bmccreds/test_main.py
IM: CRAYSAT-1920
Reviewer: Ryan
(cherry picked from commit d428ea727913a12529b893a290613f20ea194000)
_This backports `sat bmccreds` improvements to release/3.25 for inclusion in CSM 1.5 and SAT 2.6._
- https://github.com/Cray-HPE/sat/pull/202
_Resolves [CRAYSAT-1920](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1920)._
_See linked PR._
_See linked PR._
=> CRAYSAT-1920: Backport `sat bmccreds` improvements to SAT 2.6/CSM 1.5

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
_Remove the ability to read VCS password from a file which is no longer necessary._
_Resolves [CRAYSAT-1913](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1913)._
_Merge this after https://github.com/Cray-HPE/python-csm-api-client/pull/43_
Yet to be tested on the system where it upgrades from CSM 1.5.x to 1.6.1
_Since we didn't get system to test the changes when CSM upgrade from 1.5.x to 1.6.0,  Test this on update-cfs-config stage and prepare images stage when upgrading from CSM 1.5.x to 1.6.1 in future_
_Risk is low as we are removing only the code redundancy_
=> CRAYSAT-1913: Remove the ability to read VCS password from a file

CHANGELOG.md, sat/config.py
_Fix unused code in `get_config_value` for handling infinite BOS timeouts_
_Resolves [CRAYSAT-1913](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1913)._
Fanta
_Test the changes with shutdown/boot/reboot with bos-operations_
_Minimal_
=> CRAYSAT-1916: Fix unused code in `get_config_value` for handling infinite BOS timeouts

CHANGELOG.md, sat/cli/status/status_module.py
The `CFSStatusModule` still had hard-coded property names for the properties of a CFS component, and these property names were only valid for CFS v2, so `sat status` only showed CFS fields when CFS v2 was used. Update the mapping so that it correctly maps CFS properties to the `sat status` column names for both CFS v2 and v3.
* Resolves CRAYSAT-1929
* noname
Built `cray-sat` image and tested on `noname` with both CFS versions, that is:
* `sat status --cfs-version v2`
* `sat status --cfs-version v3`
Low risk change which only affects `sat status`.
=> CRAYSAT-1929: Fix CFS fields in `sat status` for CFS v3

tests/cli/bootprep/input/test_base.py, tests/cli/bootprep/input/test_session_template.py
Add unit tests for usage of the `jinja_rendered` decorator on properties of the `BaseInputItem`.
Modify these unit tests to simplify them slightly and to ensure that the `SomeTestItem` class calls the `BaseInputItem` constructor, so that it sets the `jinja_env` instance attribute, which is used by the `jinja_rendered` decorator.
* Part of CRAYSAT-1917
Unit tests pass.
Low risk unit test improvements.
=> CRAYSAT-1917: Add unit tests for `jinja_rendered` decorator

CHANGELOG.md, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/session_template.py, tests/cli/bootprep/input/test_base.py, tests/cli/bootprep/input/test_session_template.py
Make the following fixes:
- Remove the `boot_set` property from `BaseInputItem`. It is not appropriate there, and it is redundant with `boot_sets` property that already exists in the `InputSessionTemplate`
- Modify the `jinja_rendered` decorator to recursively render more complex objects like lists and dictionaries. I think this is safe, but we should consider any edge cases more carefully.
- Remove the now unnecessary code that does a one-off Jinja2 rendering of `rootfs_provider_passthrough` in the `boot_sets`.
Could still use unit test enhancements that test this new ability to render fields in the boot_sets.
* Resolves …
=> CRAYSAT-1917: Fix jinja2 rendering of boot_sets data in `sat bootprep`

CHANGELOG.md, requirements.txt, sat/cli/bootprep/input/image.py
Traceback Error - "TypeError: create_image_customization_session() missing 1 required positional argument: 'image_name'" has been observed with the latest stable build of `release/3.25`
To fix this, Backport `CRAYSAT-1747: Allow passing CFS session name` to SAT 2.6 / CSM 1.5 as a solution
Incorrect logging is observed in sat bootprep logs SAT is also generating a session name, which is conflicting with session name generated in create_image_customization_session
Hence updating the `begin_image_configure` to pass session name to address sat bootprep incorrect logging
(cherry picked from commit e35ac289cfac844d98727f715c742248ce9239e7)
* Resolves …
=> CRAYSAT-1935: create_image_customization_session() missing `image_name` argument

CHANGELOG.md, sat/cli/bootprep/input/session_template.py, tests/cli/bootprep/input/test_session_template.py
This PR adds validation to check that rootfs_provider and rootfs_provider_passthrough are not empty strings
* Resolves [CRAYSAT-1895](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1895)
* drax
Changes were successful, output of testing on drax: https://gist.github.com/ethanholen-hpe/7069d94e25dc06c59ba84c05c04cfb07#file-gistfile1-txt
=> CRAYSAT-1895: add empty string handling for rootfs_provider key of boot_set

.gitignore, CHANGELOG.md, sat/cli/showrev/products.py, sat/loose_version.py, sat/util.py, tests/cli/showrev/test_products.py, tests/test_loose_version.py
Fixed the sorting of product versions for sat showrev --products as outlined in [CRAYSAT-1551](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1551)
* Resolves [CRAYSAT-1551](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1551)
* Drax: https://gist.github.com/ethanholen-hpe/6ac403f4ddff61cb0c03d66809ec5450
Tests were run on drax and tested locally, unit tests were also added for the new class.
=> CRAYSAT-1551: Fix sorting of product versions in sat showrev --products

CHANGELOG.md, sat/cli/bootprep/input/session_template.py, tests/cli/bootprep/input/test_session_template.py
Add validation to check for existence of rootfs_provider and rootfs_provider_passthrough before checking for empty string.
* Resolves [CRAYSAT-1941](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1941)
Tests added to verify functionality
None
=> CRAYSAT-1941: add validation to check for existence of rootfs_provider

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
Fixed `sat bootprep` to include the value of `ims_require_dkms` in the
created CFS configurations, even when explicitly set to `False`.
* Resolves CRAYSAT-1896
* rocket
Tested on rocket with a `bootprep` input file that defines a CFS
configuration that contains two layers, one which sets the
`ims_require_dkms` property to `True` and one which sets it to `False`.
Verified that the resulting CFS configuration contained the value for
the property in both layers. Tested in dry-run mode and regular mode for
both CFS v2 and v3.
Low risk change to just support specifying false values in CFS configurations.
=> CRAYSAT-1896: Fix `sat bootprep` to include False `ims_require_dkms`

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/auth/main.py, sat/session.py, tests/cli/bootsys/test_bos.py, tests/cli/bootsys/test_service_activity.py, tests/cli/firmware/test_firmware.py, tests/cli/slscheck/test_slscheck.py, tests/cli/swap/test_ports.py, tests/test_session.py
add error logging when unable to find token file path and unwrap ~ as home directory
* Resolves [CRAYSAT-1649](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1649)
* Change will also be needed in `<insert branch name here>`
* Merge after https://github.com/Cray-HPE/python-csm-api-client/pull/48
* Rocket
* Drax
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration …
=> CRAYSAT-1649: add error logging when unable to find token file path

CHANGELOG.md, docs/man/_sat-format-opts.rst, sat/cli/showrev/main.py, sat/cli/showrev/parser.py, sat/parsergroups.py, sat/report.py, tests/test_report.py
Added ability to sort reports by multiple fields
* Resolves [CRAYSAT-1936](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1936)
* drax
- Was downgrade tested? If not, why? yes
- Were new tests (or test issues/Jiras) created for this change? yes
=> CRAYSAT-1936: add ability to sort reports by multiple fields

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/parser.py, sat/cli/bootsys/service_activity.py, tests/cli/bootsys/test_service_activity.py, tests/test_report.py
_Update `sat bootsys` to support CFS v2 or v3_
* Resolves [CRAYSAT-1923](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1923)
* Resolves [CRAYSAT-1847](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1847)
fanta
Test `sat bootsys` for both cfs v2 and cfs v3 version including the paging property
_Low_
=> CRAYSAT-1923: Update `sat bootsys` to support CFS v2 or v3

CHANGELOG.md, sat/cli/showrev/main.py
fix sorting warnings in sat showrev
* Resolves [CRAYSAT-1947](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1947)
* Rocket
_Are there known issues with these changes? Any other special considerations?_
No
=> CRAYSAT-1947: fix sorting warnings in sat showrev

CHANGELOG.md, docs/man/sat-status.8.rst, sat/cli/status/constants.py
_Add new HSM Types, namely `CabinetPDU`, `CabinetPDUController`, `CabinetPDUPowerConnector` and
`MgmtSwitch` in `sat status`_
* Resolves [CRAYSAT-1875](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1875)
* Odin
Tested with `sat status` command for all the types including  `CabinetPDU`, `CabinetPDUController`, `CabinetPDUPowerConnector` and  `MgmtSwitch` 
_Low_
=> CRAYSAT-1875: Add new HSM types to `sat status`

CHANGELOG.md, sat/cli/bootsys/service_activity.py
_Fixed the traceback error encountered during session checks in CFS v2 when using a smaller page size._
* Resolves [CRAYSAT-1945](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1945)
* starlord
Tested cfs v2 and cfs v3 session checks for both lower and higher page size
_Low_
=> CRAYSAT-1945: Fix traceback error of session checks in CFS v2

CHANGELOG.md, sat/cli/swap/blade.py, tests/cli/swap/test_blade.py
Fix a traceback that occurs in `sat swap blade` when the node classes reported by HSM includes both "Mountain" and "Hill" for a single blade.
This probably indicates some sort of configuration problem in HSM, but the behavior of `sat swap blade` is the same for both Mountain and Hill, so we can log a warning and proceed in this case.
* Resolves CRAYSAT-1948
Unit tested only so far.
Introduces some risk to the `sat swap blade` command, but unit tests are pretty good for the modified `blade_class` property.
Still needs to be tested on a system.
=> CRAYSAT-1948: Fix traceback in `sat swap blade`

CHANGELOG.md, sat/apiclient/bos.py, sat/cli/bootprep/input/session_template.py, tests/apiclient/test_bos.py
Drop internal default values for rootfs_provider{,passthrough} from sat bootprep
* Resolves [CRAYSAT-1942](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1942)
* drax
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
_Are there known issues with these changes? Any other special considerations?_
=> CRAYSAT-1942: Drop internal default values for rootfs_provider{,passthrough} from sat bootprep

CHANGELOG.md, sat/cli/status/status_module.py, tests/cli/status/test_status_module.py
_Drop the `Arch` field from `sat status`_
_When displaying the `sat status` of the components, do not include `Arch` field as it is hardcoded to X86 and thus meaningless or misleading to the end user for all the types except for `Node` type._
* Resolves [CRAYSAT-1930](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1930)
* Tyr
Tested `sat status` command for all the types which should drop `Arch` field except for Node type as it is distinguishing the Arch type …
=> CRAYSAT-1930: Drop the `Arch` field from `sat status`

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
Bumps [jinja2](https://github.com/pallets/jinja) from 3.1.4 to 3.1.5.
- [Release notes](https://github.com/pallets/jinja/releases)
- [Changelog](https://github.com/pallets/jinja/blob/main/CHANGES.rst)
- [Commits](https://github.com/pallets/jinja/compare/3.1.4...3.1.5)
---
updated-dependencies:
- dependency-name: jinja2 dependency-type: direct:production ...
Signed-off-by: dependabot[bot] <support@github.com>
(cherry picked from commit a5181ef6c699f0068f7de223ce3472e84bd2a1f8)
* Resolves CRAYSAT-1974
- Were the …
=> Backport CRAYSAT-1974 Bump jinja2 from 3.1.4 to 3.1.5

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/input/configuration.py
_Stop resolving branch names to commit hashes from `sat bootprep` in cfs v3. Use `drop_branches` parameter supported by cfs for v3_
* Resolves [CRAYSAT-1784](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1784)
* Will merge this after merging https://github.com/Cray-HPE/python-csm-api-client/pull/53
rocket
Test with `sat bootprep` command for both cfs v2 and v3. v3 should resolve the branch using `drop_branches` parameter. v2 will resolve the branches from `sat …
=> CRAYSAT-1784: Support for `drop_branches` in CFS v3

CHANGELOG.md, sat/cli/bootsys/mgmt_power.py, tests/cli/bootsys/test_mgmt_power.py
Resolved repeated libceph errors which delays shutdown of  Kubernetes worker nodes during `sat bootsys`
* Resolves [CRAYSAT-1887](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1887)
* fanta
Do the system shutdown and see the console logs that should remove the repeated libceph errors after unmounting ceph/s3fs/rbd devices.
If target is …
=> CRAYSAT-1887: Resolve repeated libceph errors

CHANGELOG.md, docker_scripts/config-docker-sat.sh
_Fixed build failure due to change in location of `kubectl` version file._
* Resolves [CRAYSAT-1985](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1985)
wasp ( CSM 1.7.0)
Built the container image, downloaded to wasp, and ran the
CoreV1Api.list_node method in a Python interpreter in the sat bash
shell.
Also ran sat bootprep run against a simple input file that defined a
single CFS configuration, built an image from a recipe, and then
configured that image with CFS. …
=> CRAYSAT-1985: Fix build failure

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
Fixed `CryptographyDeprecationWarning` message by upgrading `paramiko` to 3.4.1
* Resolves [CRAYSAT-1977](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1977)
* drax
Test the module where cryptography or paramiko has been used
_Low_
=> CRAYSAT-1977: Fix `CryptographyDeprecationWarning` message

CHANGELOG.md, sat/cli/slscheck/main.py
_Add INFO-level log message to output of `sat slscheck` when consistent_
* Resolves [CRAYSAT-1961](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1961)
* development system
* fanta
- Tested `sat slscheck` command before and after changes with various options where there are no inconsistencies. It should print info messages
_N/A_
=> CRAYSAT-1961: Add output when there is no inconsistencies from `slscheck`

CHANGELOG.md, sat/cli/bootprep/main.py
Fixed bug introduced in CRAYSAT-1652 local variable 'skipped_images' referenced before assignment
* Resolves CRAYSAT-1994
* Gamora
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Yes
- Was downgrade tested? If not, why? yes
- Were new tests (or test issues/Jiras) created for this change? yes …
=> CRAYSAT-1994: fixed local variable 'skipped_images' referenced before assignment

CHANGELOG.md, docs/man/sat-bootprep.8.rst, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/input/image.py, sat/cli/bootprep/input/instance.py, sat/cli/bootprep/main.py, sat/cli/bootprep/parser.py, tests/cli/bootprep/test_main.py
_Support `debug-on-failure` of cfs v3 in `sat bootprep`_
* Resolves [CRAYSAT-1991](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1991)
* fanta
- Tested with `sat bootprep run` command by adding `--debug-on-failure` which should update the cfs session debug-on-failure to true to get logs even when container torned. Without adding …
=> CRAYSAT-1991: Support `debug_on_failure` of CFS V3

CHANGELOG.md, sat/cli/status/status_module.py
_Add HSM lock status to output of `sat status`_
* Resolves [CRAYSAT-1584](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1584)
* Gamora
Test the `sat status` command that should give lock status field also with this change.
_Are there known issues with these changes? Any other special …
=> CRAYSAT-1584: Add HSM lock status to output of `sat status`

CHANGELOG.md, sat/cli/bootprep/input/image.py
Resolved create_image_customization error due to unexpected keyword 'debug_on_failure'` in cfs v3
`TypeError: create_image_customization_session() got an unexpected keyword argument 'debug_on_failure'`
* Resolves [CRAYSAT-1999](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1999)
* fanta
- Run `sat bootprep` to check all the test cases both …
=> CRAYSAT-1999: Resolve image_customization_error for `debug_on_failure`

CHANGELOG.md, sat/cli/bootprep/errors.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/test_validate.py
Fix the `__str__` method of `EnhancedValidationError` to properly handle the case where the validation error occurs because the instance object matches more than exactly one subschema in a `oneOf`. When this occurs, the `jsonschema.ValidationError` does not contain any `context`, and the `message` attribute just contains a message to the effect of "<instance> is valid under each of <oneOf subschemas>".
Fix this issue by explicitly checking whether "is valid under each" occurs in the message for the `ValidationError` in the `__str__` method. In addition, if the `context` is empty in the `best_context` method, simply return the empty list because there is no additional context to report.
With this fix, it is no longer necessary to add the `not:` subschemas, so remove them. The schema is …
=> CRAYSAT-2000: Fix `EnhancedValidationError.__str__`

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/cli/bootprep/main.py, sat/cli/showrev/products.py
A new version of cray-product-catalog is available that greatly improves
performance of loading the product catalog when instantiating a
`ProductCatalog` instance. It also adds a `shallow` boolean parameter
that causes it to only load the data from the main ConfigMap. This
ConfigMap contains all the data used by `sat bootprep`, so update `sat
bootprep` to pass `shallow=True` to further improve performance.
* Resolves CRAYSAT-1944
* rocket
Tested by running SAT functional tests on rocket with this new cray-sat
image.
Also tested `sat showrev` by comparing the output before this change to
the output after this change.
There is some risk because the cray-product-catalog code was significantly refactored. However, this is being tested well via automated SAT functional tests.
=> CRAYSAT-1944: Update cray-product-catalog and use shallow load

CHANGELOG.md, sat/cli/bootsys/hostkeys.py
Skip unparsable known_hosts entries in get_ssh_client to prevent "`NoneType` object has no attribute `hostnames` from get_ssh_client"
* Resolves [CRAYSAT-2032](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-2032), [CAST-38540](https://jira-pro.it.hpe.com:8443/browse/CAST-38540)
* rocket
Test the FilteredHostKeys by taking valid and invalid …
=> CRAYSAT-2032: Fix `NoneType` object error from get_ssh_client

CHANGELOG.md, sat/system/component.py, tests/system/test_component.py
Ensure that multi-value fields in the output of `sat hwinv` are printed in
sorted order, so the output remains consistent across executions. Updated
unit tests to verify that multi-value fields are sorted as expected in the
output.
Also swapped order of arguments in several other calls to `assertEqual`
since the order is supposed to be (expected, actual).
* Resolves CRAYSAT-2026
* wasp
Tested by pulling new cray-sat image and running `sat hwinv
--summarize-nodes` on wasp where both the memory manufacturer and memory
device type fields have multiple values on a couple nodes. Ensured the
comma-separated list of values was always sorted.
Pretty low-risk isolated change to `sat hwinv` summary behavior.
=> CRAYSAT-2026: Ensure sorted output for multi-value fields in `sat hwinv`
