CHANGELOG.md, docs/man/sat-bootsys.8.rst
This change updates the text of the `bootsys` man page. It removes
outdated information and updates the text of the `Stages` section to
accurately describe each stage's behavior.
* Resolves [CRAYSAT-1480](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1480)
Build docs with `make`.
N/A
=> CRAYSAT-1480: Update bootsys manpage

CHANGELOG.md, docs/man/sat-bootsys.8.rst, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt, sat/apiclient/ims.py, sat/cli/bootprep/image.py, sat/cli/bootprep/input/image.py, sat/cli/bootprep/validate.py, sat/config.py, sat/parser.py, sat/recipe.py, sat/waiting.py, tests/cli/bootsys/test_bos.py, tests/test_recipe.py
Merge main branch into release/3.19 branch to include changes and bugfixes included in version 3.19.1. See `CHANGELOG.md` for full list of changes.
* Part of [CRAYSAT-1550](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1550)
See individual commits for testing description.
No known risks.
=> Merge main to release/3.19

.github/workflows/license-check.yaml, CHANGELOG.md, sat/recipe.py, tests/test_recipe.py
This will create a new stable build of 3.19.2. See CHANGELOG.md for description of changes.
* Required for [CRAYSAT-1552](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1552)
See individual commit messages.
No known risks.
=> Fast-forward release/3.19 branch to 3.19.2

sat/apiclient/jobstat.py, tests/apiclient/test_jobstat.py
Commit Change:
- Changed Jobstat error structure and codes
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_bugfix
* PR-42104
* PE-43237
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Slice
Testing:
- Tested by …
=> PE-43237: Match jobstat error structure and code

sat/cli/jobstat/main.py
Commit Changes:
- Using textwrapper on apid, jobid, and command to print long lines in fixed width
- Printing each node in new line for nodelist
PE-43685
* Resolves [issue id](issue link)
* Change will also be needed in `PE-42104-sat-jobstat` 
- Tested on laptop against jobstat running on slice
* `Slice`
_How were the changes tested and success verified? If schema changes were part of this …
=> PE-43685: Fix long commands in SAT jobstat cli output

sat/apiclient/jobstat.py, sat/cli/jobstat/main.py
- Remove full path for mpiexec or aprun
- show only first 8 chars for apid
- 
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* `Slice`
_How were the changes tested …
=> PE-43843,PE-43844: Reduce sat jobstat table width

CHANGELOG.md, docker_scripts/config-docker-sat.sh
See commit messages
* Resolves CRAYSAT-1633
See commit messages
=> CRAYSAT-1633: Handle kubectl version more predictably

.gitignore, CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/bos.py, sat/cli/bootsys/parser.py, sat/cli/bootsys/stages.py, tests/cli/bootsys/test_bos.py
CRAYSAT-1643 adding BOS reboot to SAT bos-operations
* Resolves CRAYSAT-1643
- Tested on Frigg
=> CRAYSAT-1643: Add BOS reboot to bos-operations

.github/workflows/license-check.yaml, Dockerfile, Jenkinsfile.github, Makefile, docker_scripts/config-docker-sat.sh
See commit messages
Built images and ran a basic sanity test on internal system.
=> Required authentication changes for SAT 3.19

CHANGELOG.md
* Declare version 3.20.0 in the change log
* Add missing entries for fixes to bootprep man page.
Test Description: Viewed the change log.
=> CRAYSAT-1651: Prepare change log for SAT 2.5 release

CHANGELOG.md, docs/man/sat-showrev.8.rst, sat/cli/showrev/products.py, tests/cli/showrev/test_products.py
See commit message
* Resolves CRAYSAT-1628
* 
See commit message
This is a relatively low-risk change and it has been thoroughly tested.
=> CRAYSAT-1628: Remove "active" field from output of 'sat showrev'

CHANGELOG.md
Cut version 3.21.0 in the changelog. I bumped the minor version due to new options added to the CLI.
=> CRAYSAT-1661: Prepare new release IUF fixes for SAT 2.5

CHANGELOG.md, docs/man/sat-bootsys.8.rst, sat/cli/bootsys/parser.py
Fast-forward release/3.21 branch to match latest main branch, which includes the fix for CRAYSAT-1664.
=> Fast-forward release/3.21 to latest main

CHANGELOG.md, docker_scripts/config-docker-sat.sh
Create 3.22.0 release of cray-sat container image.
* Resolves [CRAYSAT-1719](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1719)
=> CRAYSAT-1719: Prepare 3.22.0 release

CHANGELOG.md, docker_scripts/config-docker-sat.sh
CRAYSAT-1738: Fix date in 3.24.0 changelog entry
Merge pull request #148 from Cray-HPE/CRAYSAT-1738-fix-changelog-date
=> Merge from integration_2023-06-23_12.38 to main (Cray-HPE/sat) 06-23

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
This PR contains three dependabot PRs merged into a single PR for ease of testing.
* Resolves [CRAYSAT-1751](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1750)
* mug
Downloaded container image to mug and tested `sat status` on mug.
Ran `sat bootprep generate-docs` and verified generated HTML looked correct.
Low risk.
=> CRAYSAT-1751: Address security vulnerabilities through dependabot

CHANGELOG.md, sat/cli/bootsys/state_recorder.py, sat/cli/setrev/main.py, sat/cli/showrev/system.py, sat/util.py, tests/test_util.py
error exception is added to handle and continue instead of aborting the cmd run
* Resolves [CRAYSAT-1676](https://jira-pro.it.hpe.com:8443/browse/)
* will be tested on csm system
TODO
Low risk.
=> CRAYSAT-1676: showrev bug fix when run without option

CHANGELOG.md, docker_scripts/config-docker-sat.sh, requirements-dev.lock.txt, requirements.lock.txt, sat/cli/bootsys/state_recorder.py, sat/cli/setrev/main.py, sat/cli/showrev/system.py, sat/util.py, tests/test_util.py
Fast-forward release/3.25 to match the latest main branch, which has some fixes we want to release in SAT 2.6 and CSM 1.5.
* Resolves [CRAYSAT-1778](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1778)
* Resolves [CRAYSAT-1766](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1766)
* mug
A smoke test was performed as described in #167.
Testing was performed individually for each fix in this update to the release/3.25 branch.
This is pretty low risk.
=> Release version 3.25.5

sat/cli/bootsys/platform.py
changes applied to address "sat bootsys boot --stage platform-services" error. 
A loop is introduced to iterate 3 times over the chron job recreation in order to overcome errors seen with instant execution after kubelet restart 
* Resolves [CRAYSAT-1786](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1786)
* Change will also be needed in `1.6 and 1.5`
Yet to be performed 
will update once tested
Low risk
=> CRAYSAT:1786 addressing the issue during bootsys platform-services

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
Reviewer:Ryan
Adding the security fixes to the branch to get them into csm 1.5 as well
* Resolves [CRAYSAT-1792](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1792)
* *Resolves [CRAYSAT-1785](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1785)
* `MUG
* 
Tested for sat commands looks good without any issues
low risk
=> CRAYSAT-1792:Adding security updates

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
IM:CRAYSAT-1795
Reviewer:Ryan
Paramiko is upgraded to address the security vulnerability 
* Resolves [CRAYSAT-1795](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1795)
`
* MUG
Test went fine without issues, SAT commands were tested on it.
Low risk
=> addressing security vulnerability of paramiko

.github/workflows/license-check.yaml, CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, sat/filtering.py, sat/logging.py, tests/test_filtering.py, tests/test_logging.py
Merge main to release/3.27 to get a stable build of the latest 3.27.2.
This will be merged locally and pushed to get a true fastforward merge without a merge commit, which git does not allow through the pull request web UI, unfortunately.
* CRAYSAT-1800
* CRAYSAT-1795
See PRs to main.
See PRs to main.
=> Update release/3.27 to 3.27.2

CHANGELOG.md, docs/man/sat-status.8.rst
IM: CRAYSAT-1801
Reviewer: Ryan
_Update description for all the fields in sat status man page_
_[CRAYSAT-1801](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1801)_
yet to test
_TO DO_
_Low_
=> CRAYSAT-1801: Updating sat-status man page

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt
_Resolve dependabot alerts `certifi`_
https://github.com/Cray-HPE/sat/pull/235
See the above PR
_See the above PR_
=> CRAYSAT-1881: Backport cray-sat 3.28.11

CHANGELOG.md
_Review and improve the changelog entries to make sure they're complete, clear, and consistent to merge into main._
[CRAYSAT-1885](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1885)
_N/A_
=> CRAYSAT-1885: Review and Improve Changelog entries

CHANGELOG.md, sat/main.py
Merge main to release/3.30 to get a stable build of the latest 3.30.1.
This will be merged locally and pushed to get a true fastforward merge without a merge commit, which git does not allow through the pull request web UI, unfortunately.
*  [CRAYSAT-1392](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1392)
See PRs to main.
See PRs to main.
=> Update release/3.30 to 3.30.1 

CHANGELOG.md, docker_scripts/config-docker-sat.sh, sat/cli/bootsys/mgmt_power.py, tests/cli/bootsys/test_mgmt_power.py
_Backport `cray-sat` image from  3.34.5 to 3.34.7_
* Resolves https://github.com/Cray-HPE/sat/pull/324
* Resolves https://github.com/Cray-HPE/sat/pull/327
_See the linked PRs._
_See the linked PRs_
=> Backport `cray-sat` image to 3.34.7

CHANGELOG.md, sat/cli/bootprep/image.py
Prompt individually for each image that already exists in sat bootprep
* Resolves CRAYSAT-1619
* Change will also be needed in `<insert branch name here>`
* rocket
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yes
- Was upgrade …
=> CRAYSAT-1619: prompt individually for existing images

CHANGELOG.md, sat/cli/bootprep/image.py, sat/cli/bootprep/input/base.py, sat/cli/bootprep/input/image.py, sat/data/schema/bootprep_schema.yaml
Add ability to specify skip or overwrite of existing items in bootprep file
* Resolves CRAYSAT-1949
* Documentation changes required in https://github.com/Cray-HPE/docs-csm/pull/5860
* Rocket
* Gamora
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yes
- Was downgrade tested? If not, why? …
=> CRAYSAT-1949: Add ability to specify skip or overwrite behavior in bootprep file

CHANGELOG.md, sat/cli/bootsys/parser.py, sat/cli/bootsys/platform.py, tests/cli/bootsys/test_platform.py
_Reduced ceph time to become healthy and reduced boot time while powered on._
* Resolves [CRAYSAT-1886](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1886)
* drax
Tested by powering on the system and observed that ceph becomes healthy before the completion of booting process.
_Low_
=> CRAYSAT-1886: Ceph takes long time to become healthy

CHANGELOG.md, sat/cli/bootprep/image.py, sat/cli/bootprep/main.py, tests/cli/bootprep/test_main.py
Always print report even when some items fail
* Resolves CRAYSAT-1690
* gamora
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yes
- Was downgrade tested? If not, why? yes
- Were new tests (or …
=> CRAYSAT-1690: Always print report even when some items fail

CHANGELOG.md, sat/cli/bootprep/constants.py, sat/cli/bootprep/image.py, sat/cli/bootprep/main.py, tests/cli/bootprep/test_main.py
Include skipped items in sat bootprep report
* Resolves CRAYSAT-1652
* `<development system>`
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
_Are there known issues with these …
=> CRAYSAT-1652: include skipped items in sat bootprep report

CHANGELOG.md, sat/cli/slscheck/parser.py
_Added `CDUMgmtSwitch` to the type of `sat slscheck`_
* Resolves [CRAYSAT-1517](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1517)
* hela
- Test the `sat slscheck` on the system where CDU Management switch is there.
_No_
=> CRAYSAT-1517: Add `CDUMgmtSwitch` type to `sat slscheck`

CHANGELOG.md, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
log HTTP request bodies at debug level
* Resolves CRAYSAT-1846
* [python-csm-api-client PR](https://github.com/Cray-HPE/python-csm-api-client/pull/59)
* Merge after https://github.com/Cray-HPE/python-csm-api-client/pull/59
* gamora
* rocket
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? yes …
=> CRAYSAT-1846: log HTTP request bodies at debug level

CHANGELOG.md, sat/util.py
Add visibility for environment variables inside of the container.
* Resolves CRAYSAT-1979
* Change will also be needed in https://github.com/Cray-HPE/sat-podman/pull/38
* fanta
* gamora
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation …
=> CRAYSAT-1979: add visibility for environment variables inside of container

CHANGELOG.md, sat/cli/bootprep/errors.py, sat/cli/bootprep/input/configuration.py, sat/data/schema/bootprep_schema.yaml, tests/cli/bootprep/test_validate.py
Add `sat bootprep` support for commit hash in source-based CFS configuration layer
* Resolves [CRAYSAT-2000](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-2000)
* rocket
- Test `sat bootprep` for sources, both adding branch or adding commit
_Are there known issues with these changes? Any other special considerations?_NO
=> CRAYSAT-2000: Add commit hash in source-based CFS

CHANGELOG.md, Dockerfile, requirements-dev.lock.txt, requirements.lock.txt, requirements.txt
* Bump urllib3 from 1.26.19 to 2.5.0
Bumps [urllib3](https://github.com/urllib3/urllib3) from 1.26.19 to 2.5.0.
- [Release notes](https://github.com/urllib3/urllib3/releases)
- [Changelog](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst)
- [Commits](https://github.com/urllib3/urllib3/compare/1.26.19...2.5.0)
---
updated-dependencies:
- dependency-name: urllib3 dependency-version: 2.5.0 dependency-type: direct:production ...
* "dependabot/pip/urllib3-2.5.0: bump alpine version to 3.16 for python v3.10.14"
* "dependabot/pip/urllib3-2.5.0: update license"
* "dependabot/pip/urllib3-2.5.0: update botocore"
* "dependabot/pip/urllib3-2.5.0: update boto3"
* "dependabot/pip/urllib3-2.5.0: update s3transfer to 0.10.0"
* "dependabot/pip/urllib3-2.5.0: update changelog"
---------
_Summarize …
=> CRAYSAT-2003: Resolve dependabot alert for urllib3 backport to 3.35
